import { z } from 'zod';

export const mechanicsRuleId = z.enum([
  'punctuation-spacing', 'period', 'comma', 'semicolon', 'colon', 'em-dash',
  'quotation-marks', 'parentheses', 'brackets', 'slash', 'preferred-spelling',
  'hyphen', 'capitalization-sentence-start', 'proper-names-trademarks',
  'titles-positions', 'diseases-disorders-therapies-theories',
  'work-titles-headings', 'tests-measures-titles', 'numbered-nouns',
  'experimental-conditions-groups', 'factors-variables-effects', 'italics',
  'reverse-italics', 'abbreviation-use', 'abbreviation-definition',
  'abbreviation-format', 'measurement-unit-abbreviations', 'time-abbreviations',
  'latin-abbreviations', 'chemical-compound-abbreviations',
  'gene-protein-abbreviations', 'numbers-as-numerals', 'numbers-as-words',
  'numbers-numerals-and-words', 'ordinal-numbers', 'decimal-fractions',
  'roman-numerals', 'commas-in-numbers', 'plurals-of-numbers',
  'effective-statistical-presentation', 'references-for-statistics', 'formulas',
  'statistics-in-text', 'statistical-symbols-abbreviations',
  'statistical-spacing-alignment-punctuation', 'equations-in-text',
  'displayed-equations', 'statistical-mathematical-copy', 'list-guidelines',
  'lettered-lists', 'numbered-lists', 'bulleted-lists',
]);

export type MechanicsRuleId = z.infer<typeof mechanicsRuleId>;

export interface Apa7VerifiedMechanicsRule {
  id: MechanicsRuleId;
  label: string;
  manualSection: `6.${number}`;
  manualPrintedPages: string;
  status: 'verified';
  rules: string[];
  citationTreatment: string[];
  referenceTreatment: string[];
  refuseWhen: string[];
}

const verified = (rule: Omit<Apa7VerifiedMechanicsRule, 'status' | 'citationTreatment' | 'referenceTreatment' | 'refuseWhen'> & Partial<Pick<Apa7VerifiedMechanicsRule, 'citationTreatment' | 'referenceTreatment' | 'refuseWhen'>>): Apa7VerifiedMechanicsRule => ({
  ...rule,
  status: 'verified',
  citationTreatment: rule.citationTreatment ?? ['Aplica la regla mecánica sin alterar autor, fecha, localizador, texto citado ni alcance de la atribución.'],
  referenceTreatment: rule.referenceTreatment ?? ['Conserva los datos de la fuente y la puntuación estructural de la plantilla APA; no “corrijas” nombres, títulos, DOI o URL por conjetura.'],
  refuseWhen: rule.refuseWhen ?? ['La aplicación cambiaría un dato, nombre, símbolo, cita textual, DOI o URL.', 'La norma lingüística o disciplinar aplicable no se ha identificado.', 'Se intenta completar o corregir información bibliográfica sin consultar la fuente.'],
});

export const mechanicsRules: Record<MechanicsRuleId, Apa7VerifiedMechanicsRule> = {
  'punctuation-spacing': verified({ id: 'punctuation-spacing', label: 'Espacio después de los signos de puntuación', manualSection: '6.1', manualPrintedPages: '153-154', rules: ['Usa un espacio después de signos finales, comas, dos puntos, puntos y coma, puntos entre elementos de referencias e iniciales de nombres.', 'No insertes espacios dentro de abreviaturas, etiquetas anonimizadas ni razones como 1:4.', 'No agregues espacios para partir manualmente DOI o URL.'], referenceTreatment: ['Usa un espacio después de cada punto estructural y entre iniciales; conserva sin espacios internos DOI, URL y abreviaturas establecidas.'] }),
  period: verified({ id: 'period', label: 'Punto', manualSection: '6.2', manualPrintedPages: '154', rules: ['Usa punto al final de una oración completa y en abreviaturas que lo requieren.', 'No pongas punto tras títulos o encabezados independientes, DOI o URL finales, ni abreviaturas de unidades métricas.', 'En citas en bloque, el punto de la cita precede a la cita parentética.'], citationTreatment: ['En cita corta, la cita parentética normalmente precede al punto final; en bloque, el punto va antes del paréntesis.', 'No añadas punto dentro de una cita textual si no pertenece al original salvo el ajuste permitido al final.'], referenceTreatment: ['Separa elementos de la referencia con puntos según la plantilla, pero no añadas punto después de DOI o URL.'] }),
  comma: verified({ id: 'comma', label: 'Coma', manualSection: '6.3', manualPrintedPages: '155-156', rules: ['Usa coma tras frases introductorias cuando facilite lectura, para delimitar información no restrictiva y entre elementos de una serie.', 'Úsala para separar grupos de tres dígitos solo cuando la convención numérica aplicable lo indique.', 'No separes sujeto y verbo ni pares esenciales solo por producir una pausa oral.'], citationTreatment: ['Separa autor y año, año y localizador, y elementos de una misma cita según las reglas de citación.', 'No introduzcas una coma que convierta una cláusula restrictiva en explicativa o cambie el alcance de la fuente.'], referenceTreatment: ['Conserva comas entre apellidos e iniciales, autores, fecha completa y datos editoriales conforme a cada plantilla.'] }),
  semicolon: verified({ id: 'semicolon', label: 'Punto y coma', manualSection: '6.4', manualPrintedPages: '156', rules: ['Úsalo entre dos cláusulas independientes no unidas por conjunción y para separar series cuyos elementos ya contienen comas.', 'No lo uses para unir un fragmento dependiente como si fuera oración completa.'], citationTreatment: ['Separa obras distintas dentro de una cita parentética múltiple con punto y coma.', 'Dentro de la misma obra, no sustituyas por punto y coma la coma que separa autor, año o localizador.'], referenceTreatment: ['No se usa punto y coma para separar autores de una referencia; aplica coma y ampersand según corresponda.'] }),
  colon: verified({ id: 'colon', label: 'Dos puntos', manualSection: '6.5', manualPrintedPages: '156-157', rules: ['Usa dos puntos después de una cláusula introductoria completa para presentar ampliación, lista o proporción.', 'No los pongas inmediatamente después de un verbo o preposición que ya introduce la lista.', 'En razones numéricas no dejes espacios alrededor del signo.'], citationTreatment: ['No reemplaces con dos puntos la coma antes de un localizador de cita.', 'Conserva los dos puntos originales en títulos o material citado.'], referenceTreatment: ['Conserva título y subtítulo separados por dos puntos y aplica mayúsculas según el tipo de título.'] }),
  'em-dash': verified({ id: 'em-dash', label: 'Raya', manualSection: '6.6', manualPrintedPages: '157-158', rules: ['Usa la raya para una interrupción brusca o inciso enfático y el guion para unir elementos; no son intercambiables.', 'No insertes espacios a ambos lados de la raya según el formato APA.', 'Evita abusar de rayas cuando comas o paréntesis expresen mejor la relación.'], citationTreatment: ['Una omisión en cita se marca con puntos suspensivos, no con raya inventada.', 'Conserva una raya que pertenezca al texto original citado.'] }),
  'quotation-marks': verified({ id: 'quotation-marks', label: 'Comillas', manualSection: '6.7', manualPrintedPages: '158-159', rules: ['Usa comillas para citas textuales cortas, material lingüístico como ejemplo irónico o inventado y títulos que la regla específica coloca entre comillas.', 'No uses comillas para enfatizar, introducir términos técnicos después de su primera aparición ni marcar categorías de escala que deben ir en cursiva.', 'Respeta la convención de comillas dobles y simples del idioma y el anidamiento.'], citationTreatment: ['Menos de 40 palabras: integra entre comillas y añade autor, año y localizador; 40 o más: bloque sin comillas.', 'Las comillas interiores de una cita se conservan según el anidamiento; no sugieren una fuente nueva.'], referenceTreatment: ['No encierres títulos de artículos, capítulos o páginas entre comillas en la lista de referencias.'] }),
  parentheses: verified({ id: 'parentheses', label: 'Paréntesis', manualSection: '6.8', manualPrintedPages: '159-160', rules: ['Úsalos para información complementaria, abreviaturas definidas, citas parentéticas, valores estadísticos y enumeraciones breves.', 'Evita paréntesis anidados; usa corchetes dentro de material ya entre paréntesis.', 'No encierres información esencial de forma que parezca prescindible.'], citationTreatment: ['Las citas parentéticas completas van entre paréntesis; en una cita narrativa solo año y localizador se parentetizan según el contexto.', 'Evita yuxtaponer dos pares de paréntesis: combina la información de forma legible.'], referenceTreatment: ['La fecha y determinados datos de edición, número o descripción usan paréntesis según la plantilla exacta.'] }),
  brackets: verified({ id: 'brackets', label: 'Corchetes', manualSection: '6.9', manualPrintedPages: '160-161', rules: ['Usa corchetes para insertar aclaraciones dentro de una cita, para material dentro de paréntesis y para descripciones de obras en referencias.', 'No uses corchetes para indicar una alteración que APA permite sin explicación, como cambiar mayúscula inicial.', 'Distingue texto del autor de una adición editorial.'], citationTreatment: ['Encierra con corchetes una palabra añadida para aclarar una cita y usa “[sic]” solo cuando sea necesario señalar un error relevante del original.', 'No inventes texto entre corchetes para completar una fuente.'], referenceTreatment: ['Las descripciones de formato o tipo de obra se colocan entre corchetes sin cursiva después del título.'] }),
  slash: verified({ id: 'slash', label: 'Diagonal', manualSection: '6.10', manualPrintedPages: '161-162', rules: ['Usa diagonal para ciertos cocientes, unidades, alternativas establecidas y años de publicación original/reedición cuando la regla lo exige.', 'Evita “y/o”; redacta la relación lógica con precisión.', 'No uses diagonal para sustituir indiscriminadamente palabras o separar rangos.'], citationTreatment: ['Conserva la diagonal de años dobles en obras reimpresas, traducidas, clásicas o religiosas cuando corresponda.'], referenceTreatment: ['No alteres diagonales que forman parte de DOI o URL; los años dobles se aplican solo en las plantillas verificadas.'] }),
  'preferred-spelling': verified({ id: 'preferred-spelling', label: 'Ortografía preferida', manualSection: '6.11', manualPrintedPages: '162-163', rules: ['Para español consulta las autoridades lingüísticas indicadas por la edición y usa una variante consistente.', 'Conserva la ortografía preferida de nombres propios, marcas, identidades y términos técnicos oficiales.', 'Los correctores automáticos no sustituyen la revisión ni resuelven todos los usos disciplinares.'], citationTreatment: ['No modernices ni “corrijas” silenciosamente la ortografía dentro de una cita textual.'], referenceTreatment: ['Transcribe nombres de autor, títulos y fuentes como aparecen en la obra, aplicando solo las transformaciones APA permitidas.'] }),
  hyphen: verified({ id: 'hyphen', label: 'Guion', manualSection: '6.12', manualPrintedPages: '163-165', rules: ['Usa guion cuando un compuesto pueda interpretarse mal o exprese una unidad conceptual que la norma del español escriba con guion.', 'Muchos prefijos y sufijos se escriben unidos; consulta diccionario y tablas del manual en caso de duda.', 'No confundas guion con raya, signo menos ni rango numérico.', 'Evita cortar palabras manualmente al final de línea.'], referenceTreatment: ['Conserva guiones auténticos de apellidos, títulos, identificadores y URL.'] }),
  'capitalization-sentence-start': verified({ id: 'capitalization-sentence-start', label: 'Palabras que comienzan una oración', manualSection: '6.13', manualPrintedPages: '165', rules: ['Escribe con mayúscula la primera palabra de una oración completa y de una cita completa cuando la sintaxis lo requiera.', 'Después de dos puntos, usa mayúscula solo en los casos previstos por la norma del idioma y la estructura.', 'Puede cambiarse la mayúscula inicial de una cita para integrarla sin señalar la modificación.'], citationTreatment: ['La mayúscula inicial de una cita puede ajustarse a la oración; otros cambios sustantivos requieren indicación.'] }),
  'proper-names-trademarks': verified({ id: 'proper-names-trademarks', label: 'Nombres propios y nombres comerciales', manualSection: '6.14', manualPrintedPages: '165-166', rules: ['Capitaliza nombres propios y derivados que conservan referencia directa al nombre.', 'Respeta la grafía oficial de marcas, programas y productos y usa un término genérico cuando la marca no sea necesaria.', 'No añadas símbolos ® o ™ salvo que sean relevantes.'], referenceTreatment: ['Conserva la capitalización oficial de autores, organizaciones, revistas y software, sin inventar expansión de marcas o siglas.'] }),
  'titles-positions': verified({ id: 'titles-positions', label: 'Títulos y puestos de trabajo', manualSection: '6.15', manualPrintedPages: '166-167', rules: ['Capitaliza un título formal cuando precede inmediatamente al nombre como parte de él; usa minúscula en referencias genéricas o después del nombre.', 'No uses tratamientos académicos u honoríficos como sustitutos de nombres o roles de autoría.', 'Respeta la convención institucional o jurídica cuando el título forme parte oficial de una denominación.'], referenceTreatment: ['Los grados y cargos no se añaden a los nombres de autores en una referencia ordinaria.'] }),
  'diseases-disorders-therapies-theories': verified({ id: 'diseases-disorders-therapies-theories', label: 'Enfermedades, trastornos, terapias, teorías y términos relacionados', manualSection: '6.16', manualPrintedPages: '167-168', rules: ['Escribe en minúscula nombres comunes de enfermedades, trastornos, tratamientos, teorías, modelos, leyes y procedimientos.', 'Capitaliza únicamente los nombres propios contenidos en esas denominaciones.', 'No uses una mayúscula para convertir una descripción no oficial en diagnóstico o teoría formal.'], citationTreatment: ['Cita el manual diagnóstico, teoría o fuente clínica cuando se invoque su definición o criterio.'], referenceTreatment: ['Referencia la edición y versión exactas del manual, instrumento o teoría citados.'] }),
  'work-titles-headings': verified({ id: 'work-titles-headings', label: 'Títulos de obras y encabezados dentro de las obras', manualSection: '6.17', manualPrintedPages: '168-169', rules: ['Aplica estilo oración o capitalización de título según el lugar: texto, título citado, publicación periódica o encabezado.', 'Después de dos puntos o raya en un título, capitaliza la primera palabra del subtítulo cuando corresponda.', 'No traslades automáticamente la capitalización de una portada a la lista de referencias.'], citationTreatment: ['Un título usado en lugar de autor se abrevia y formatea como lo estaría la obra: cursiva para obra independiente o comillas para parte de un todo.'], referenceTreatment: ['Usa estilo oración en títulos de obras y partes; conserva capitalización de nombres propios y usa la convención de la revista para el nombre de la publicación.'] }),
  'tests-measures-titles': verified({ id: 'tests-measures-titles', label: 'Títulos de pruebas y medidas', manualSection: '6.18', manualPrintedPages: '169', rules: ['Capitaliza el nombre propio completo de una prueba o escala y usa minúscula para referencias genéricas a ella.', 'No pongas en cursiva el nombre de una prueba solo por ser un título.', 'Define abreviatura tras el nombre completo si se usará repetidamente.'], citationTreatment: ['Cita la fuente de desarrollo, validación o manual de la prueba cuando se utilice o describa.'], referenceTreatment: ['Referencia el manual, artículo o registro real de la prueba; no inventes editorial, año o versión.'] }),
  'numbered-nouns': verified({ id: 'numbered-nouns', label: 'Sustantivos seguidos de números o letras', manualSection: '6.19', manualPrintedPages: '169-170', rules: ['Capitaliza un sustantivo que identifica una parte específica de una serie numerada, como Tabla 2, Figura 3 o Apéndice A.', 'Usa minúscula para menciones genéricas o plurales no vinculados a un número específico.', 'No capitalices sustantivos ordinarios solo porque lleven un número.'], citationTreatment: ['Distingue el localizador de fuente “p. 3” de una parte interna como “Tabla 3”.'] }),
  'experimental-conditions-groups': verified({ id: 'experimental-conditions-groups', label: 'Condiciones o grupos en un experimento', manualSection: '6.20', manualPrintedPages: '170', rules: ['Usa minúscula para nombres descriptivos de condiciones y grupos salvo que contengan nombre propio.', 'Mantén etiquetas consistentes entre método, resultados, tablas y figuras.', 'Evita nombres que impliquen superioridad, normalidad o causalidad no demostrada.'] }),
  'factors-variables-effects': verified({ id: 'factors-variables-effects', label: 'Factores, variables y efectos', manualSection: '6.21', manualPrintedPages: '170-171', rules: ['Usa minúscula para nombres comunes de factores, variables y efectos salvo nombres propios.', 'Distingue el nombre conceptual, la etiqueta del modelo y el símbolo estadístico.', 'Conserva una denominación estable para evitar aparentar variables distintas.'] }),
  italics: verified({ id: 'italics', label: 'Uso de cursiva', manualSection: '6.22', manualPrintedPages: '171-173', rules: ['Usa cursiva en títulos de obras independientes, nombres de publicaciones y volumen, símbolos estadísticos y algebraicos, anclas de escala y primera aparición de términos extranjeros no naturalizados.', 'Puede usarse para una palabra como ejemplo lingüístico, pero no como énfasis general.', 'No pongas en cursiva signos de puntuación adyacentes, abreviaturas químicas, letras griegas ni números de volumen cuando la regla no lo indica.'], citationTreatment: ['En el texto, un título de obra independiente va en cursiva; el de una parte se pone entre comillas.', 'Añadir cursiva a una cita para énfasis exige indicar “[énfasis añadido]”.'], referenceTreatment: ['Aplica cursiva al elemento completo previsto por la plantilla —por ejemplo, revista y volumen o título de libro—, no al DOI/URL.'] }),
  'reverse-italics': verified({ id: 'reverse-italics', label: 'Cursiva inversa', manualSection: '6.23', manualPrintedPages: '173', rules: ['Cuando una palabra normalmente en cursiva aparece dentro de un pasaje ya en cursiva, vuelve a redonda para marcar el contraste.', 'No uses cursiva inversa si no existe una razón estructural clara.'] }),
  'abbreviation-use': verified({ id: 'abbreviation-use', label: 'Uso de abreviaturas', manualSection: '6.24', manualPrintedPages: '173-174', rules: ['Usa una abreviatura si es convencional y más reconocible o si ahorra repetición sustancial.', 'Evita abreviar términos que aparecen pocas veces o cuyo atajo confunde.', 'Después de definirla, úsala consistentemente y no alternes sin necesidad con el término completo.'], citationTreatment: ['Un autor grupal puede abreviarse solo después de presentar nombre completo y abreviatura en la primera cita, si la abreviatura es inequívoca.'] }),
  'abbreviation-definition': verified({ id: 'abbreviation-definition', label: 'Definición de abreviaturas', manualSection: '6.25', manualPrintedPages: '174-175', rules: ['Define en la primera aparición las abreviaturas no incluidas como términos habituales en diccionarios ni exceptuadas por APA.', 'No definas unidades de medida, abreviaturas temporales, latinas ni símbolos estadísticos estándar cuando la regla los exceptúa.', 'Si el primer uso está en un encabezado, define la abreviatura en el texto siguiente, no dentro del encabezado.'], citationTreatment: ['Define una abreviatura de autor grupal dentro de la primera cita y úsala después de forma consistente.'] }),
  'abbreviation-format': verified({ id: 'abbreviation-format', label: 'Formato de abreviaturas', manualSection: '6.26', manualPrintedPages: '175-176', rules: ['Respeta mayúsculas, minúsculas, puntos y plural de cada abreviatura establecida.', 'No añadas puntos a siglas o unidades que se escriben sin ellos.', 'No fabriques una sigla que pueda confundirse con otra entidad o variable.'], referenceTreatment: ['Usa las abreviaturas editoriales permitidas en referencias y conserva siglas que formen parte oficial de títulos o entidades.'] }),
  'measurement-unit-abbreviations': verified({ id: 'measurement-unit-abbreviations', label: 'Abreviaturas de unidades de medida', manualSection: '6.27', manualPrintedPages: '176-178', rules: ['Usa símbolo de unidad cuando acompaña a un valor numérico y escribe la unidad con palabras cuando no lleva número, salvo convención disciplinar.', 'Deja un espacio entre número y símbolo salvo excepciones establecidas, como algunos signos angulares.', 'No pluralices símbolos ni añadas punto.', 'Define unidades no estándar y usa unidades consistentes o informa la conversión.'] }),
  'time-abbreviations': verified({ id: 'time-abbreviations', label: 'Abreviaturas de tiempo', manualSection: '6.28', manualPrintedPages: '178', rules: ['Usa las abreviaturas temporales estándar junto a valores numéricos según el contexto técnico.', 'Escribe con palabras día, semana, mes y año cuando la abreviatura no sea estándar o pueda confundirse.', 'Distingue duración, hora del día y fecha.'] }),
  'latin-abbreviations': verified({ id: 'latin-abbreviations', label: 'Abreviaturas del latín', manualSection: '6.29', manualPrintedPages: '178-179', rules: ['En texto corrido prefiere equivalentes en español cuando sean naturales.', 'Usa abreviaturas latinas establecidas principalmente dentro de paréntesis y conserva su puntuación.', 'No confundas “p. ej.”, “es decir”, “etc.” y “cf.” ni las uses para relaciones que no expresan.'] }),
  'chemical-compound-abbreviations': verified({ id: 'chemical-compound-abbreviations', label: 'Abreviaturas de compuestos químicos', manualSection: '6.30', manualPrintedPages: '179-181', rules: ['Usa símbolos y nomenclatura química estándar y define nombres poco familiares cuando sea necesario.', 'Distingue símbolos de elementos, fórmulas, concentraciones y rutas de administración.', 'No aplique cursiva o plural gramatical a una fórmula química por analogía con una variable.'] }),
  'gene-protein-abbreviations': verified({ id: 'gene-protein-abbreviations', label: 'Nombres de genes y proteínas', manualSection: '6.31', manualPrintedPages: '181', rules: ['Usa el nombre y símbolo oficiales del gen para el organismo correcto y verifica la base de nomenclatura pertinente.', 'Distingue gen de proteína y aplica las convenciones de cursiva y mayúsculas propias de especie y disciplina.', 'Documenta alias si es necesario para evitar ambigüedad.', 'No infieras la nomenclatura desde otra especie.'], citationTreatment: ['Cita la base oficial o fuente científica cuando la nomenclatura, variante o función sea relevante.'], referenceTreatment: ['Referencia la base o publicación realmente consultada con versión o fecha de acceso cuando el contenido cambie con el tiempo.'] }),
  'numbers-as-numerals': verified({ id: 'numbers-as-numerals', label: 'Números expresados en numerales', manualSection: '6.32', manualPrintedPages: '181-182', rules: ['Usa numerales para 10 o más y para números ligados a unidades, estadísticas, porcentajes, razones, tiempo, fechas, edades, puntuaciones, dinero y posiciones numeradas.', 'Usa numeral cuando precede una unidad de medida y en funciones matemáticas.', 'No cambies un número exacto por palabra si reduce precisión.'] }),
  'numbers-as-words': verified({ id: 'numbers-as-words', label: 'Números expresados en palabras', manualSection: '6.33', manualPrintedPages: '182', rules: ['Escribe con palabras del cero al nueve cuando no pertenecen a una excepción numérica.', 'Escribe con palabras un número que comienza una oración, título o encabezado; reformula si resulta incómodo.', 'Usa palabras para fracciones comunes y expresiones universalmente aceptadas cuando no llevan medida exacta.'] }),
  'numbers-numerals-and-words': verified({ id: 'numbers-numerals-and-words', label: 'Combinación de numerales y palabras', manualSection: '6.34', manualPrintedPages: '182-183', rules: ['En una serie comparable, aplica de forma consistente la regla correspondiente a cada número.', 'Combina numeral y palabra para evitar dos numerales contiguos ambiguos y en aproximaciones redondas extensas.', 'No sacrifiques claridad por uniformidad mecánica.'] }),
  'ordinal-numbers': verified({ id: 'ordinal-numbers', label: 'Números ordinales', manualSection: '6.35', manualPrintedPages: '183', rules: ['Aplica a ordinales las mismas reglas generales que a cardinales salvo nombres, rangos o convenciones específicas.', 'Usa la forma ordinal española correcta y conserva el indicador cuando la institución lo requiera.', 'No confunda ordinal con número de una parte identificada, como Capítulo 3.'] }),
  'decimal-fractions': verified({ id: 'decimal-fractions', label: 'Fracciones decimales', manualSection: '6.36', manualPrintedPages: '183-184', rules: ['Usa cero a la izquierda para valores que pueden superar 1; omítelo en estadísticos que no pueden superar 1 cuando así lo exige APA.', 'Mantén precisión decimal coherente con la medida y el análisis.', 'No añadas decimales falsos ni redondees de forma que cambie la conclusión.', 'Usa el separador decimal exigido por el idioma o revista de manera consistente.'] }),
  'roman-numerals': verified({ id: 'roman-numerals', label: 'Números romanos', manualSection: '6.37', manualPrintedPages: '184', rules: ['Usa números romanos solo cuando forman parte de una terminología, escala, edición o nombre establecido.', 'No sustituyas numerales arábigos por romanos con fines decorativos.'], referenceTreatment: ['Conserva números romanos que formen parte oficial de congresos, volúmenes, monarcas o títulos.'] }),
  'commas-in-numbers': verified({ id: 'commas-in-numbers', label: 'Comas en los números', manualSection: '6.38', manualPrintedPages: '184', rules: ['Usa el separador de millares conforme al idioma y medio de publicación para números de cuatro o más dígitos cuando corresponda.', 'No uses separador en números de página, años, direcciones, grados de temperatura o identificadores cuando la convención los exceptúa.', 'No conviertas comas decimales en separadores de millares.'] }),
  'plurals-of-numbers': verified({ id: 'plurals-of-numbers', label: 'Plurales de números', manualSection: '6.39', manualPrintedPages: '184', rules: ['Forma el plural de números tratados como sustantivos sin apóstrofo añadido por influencia del inglés.', 'Prefiere una reformulación clara cuando el plural del símbolo o numeral resulte ambiguo.'] }),
  'effective-statistical-presentation': verified({ id: 'effective-statistical-presentation', label: 'Elección de una presentación estadística efectiva', manualSection: '6.40', manualPrintedPages: '184-185', rules: ['Elige texto, tabla o figura según cantidad, complejidad y comparación necesaria.', 'No repitas exactamente los mismos resultados en texto y tabla o figura.', 'Reporta la información suficiente para interpretar magnitud y precisión, no solo significación.'], citationTreatment: ['Los datos externos conservan su cita cualquiera sea la forma de presentación; resultados propios se llaman por tabla o figura.'], referenceTreatment: ['Una presentación propia no genera referencia; datos, métodos o visualizaciones ajenas sí conservan su fuente.'] }),
  'references-for-statistics': verified({ id: 'references-for-statistics', label: 'Referencias para estadísticas', manualSection: '6.41', manualPrintedPages: '185', rules: ['No cites fórmulas estadísticas de uso común como si cada aplicación dependiera de una fuente.', 'Cita métodos, algoritmos, correcciones, pruebas o software no familiares o específicamente derivados de otra obra.', 'Proporciona suficiente detalle para que el lector identifique el procedimiento real.'], citationTreatment: ['Usa autor-fecha para el método o software citado; una salida estadística propia no lleva cita externa.'], referenceTreatment: ['Referencia la publicación o documentación oficial del método/software efectivamente usado, incluida versión cuando sea relevante.'] }),
  formulas: verified({ id: 'formulas', label: 'Fórmulas', manualSection: '6.42', manualPrintedPages: '185', rules: ['Presenta una fórmula solo cuando ayude a comprender o replicar el análisis.', 'Define símbolos y variables que no sean estándar y conserva notación coherente.', 'No derive ni atribuya una fórmula a una fuente no consultada.'], citationTreatment: ['Cita la fuente de una fórmula ajena, adaptada o no estándar y señala las modificaciones relevantes.'], referenceTreatment: ['Incluye la obra de origen citada; la fórmula propia no genera referencia externa.'] }),
  'statistics-in-text': verified({ id: 'statistics-in-text', label: 'Estadísticas en el texto', manualSection: '6.43', manualPrintedPages: '185-186', rules: ['Incluye estadístico, grados de libertad cuando procedan, valor, dirección y probabilidad o intervalo necesario.', 'Redondea de manera consistente y con precisión suficiente.', 'No reportes solo “significativo” ni omitas resultados que contradicen la conclusión.', 'Usa tablas para conjuntos extensos.'] }),
  'statistical-symbols-abbreviations': verified({ id: 'statistical-symbols-abbreviations', label: 'Símbolos y abreviaturas estadísticas', manualSection: '6.44', manualPrintedPages: '186-193', rules: ['Usa los símbolos estadísticos estándar y define los no estándar.', 'Pon en cursiva símbolos algebraicos y estadísticos latinos cuando corresponda; no pongas en cursiva letras griegas ni abreviaturas que no son variables.', 'Distingue estadístico muestral, parámetro poblacional, estimador y abreviatura.', 'Conserva mayúsculas, minúsculas, subíndices y superíndices exactos.'] }),
  'statistical-spacing-alignment-punctuation': verified({ id: 'statistical-spacing-alignment-punctuation', label: 'Espaciación, alineación y puntuación de estadísticas', manualSection: '6.45', manualPrintedPages: '193-194', rules: ['Usa espacios alrededor de operadores binarios y los omite en signos que funcionan como prefijos cuando la notación lo exige.', 'Alinea series de valores para facilitar comparación y conserva signos, subíndices y superíndices.', 'Puntúa una expresión estadística como parte gramatical de la oración.', 'No separe un símbolo de su valor de manera que cambie la expresión.'] }),
  'equations-in-text': verified({ id: 'equations-in-text', label: 'Ecuaciones en el texto', manualSection: '6.46', manualPrintedPages: '194', rules: ['Integra ecuaciones breves en la línea y usa espaciación suficiente para que sean legibles.', 'Puntúa la ecuación conforme a su función en la oración.', 'Define símbolos no estándar antes o inmediatamente después.'], citationTreatment: ['Cita la fuente de una ecuación ajena o adaptada; el número interno de ecuación no sustituye la cita.'] }),
  'displayed-equations': verified({ id: 'displayed-equations', label: 'Ecuaciones desplegadas', manualSection: '6.47', manualPrintedPages: '194', rules: ['Despliega una ecuación si es extensa, compleja o debe citarse repetidamente.', 'Numera consecutivamente entre paréntesis cerca del margen derecho solo las ecuaciones a las que se remitirá.', 'En el texto escribe “Ecuación 3”, no una abreviatura improvisada.', 'Mantén puntuación y alineación coherentes.'] }),
  'statistical-mathematical-copy': verified({ id: 'statistical-mathematical-copy', label: 'Preparación de copia estadística y matemática', manualSection: '6.48', manualPrintedPages: '194-195', rules: ['Entrega símbolos, vallas, mayúsculas, puntuación, subíndices y superíndices exactamente como deben aparecer.', 'Inserta como imagen un carácter que el procesador no pueda representar y proporciona alternativa accesible.', 'Verifica que conversiones de formato no alteren signos o ecuaciones.', 'Sigue requisitos técnicos adicionales de la revista o institución.'] }),
  'list-guidelines': verified({ id: 'list-guidelines', label: 'Lineamientos para listas', manualSection: '6.49', manualPrintedPages: '195', rules: ['Usa listas para mostrar elementos relacionados y mantén paralelismo sintáctico y conceptual.', 'Si una serie simple cabe en una oración, sepárala con comas; si sus elementos contienen comas, usa punto y coma.', 'Elige letras, números o viñetas según si importan referencia interna, secuencia o igualdad.', 'No conviertas cualquier párrafo en lista sin beneficio de comprensión.'], citationTreatment: ['Una cita al final de un elemento respalda solo ese elemento salvo que el contexto indique inequívocamente toda la lista.'], referenceTreatment: ['Las obras citadas en cualquier elemento aparecen una sola vez en la lista general de referencias.'] }),
  'lettered-lists': verified({ id: 'lettered-lists', label: 'Listas con letras', manualSection: '6.50', manualPrintedPages: '195-196', rules: ['Dentro de una oración, identifica elementos complejos con letras minúsculas entre paréntesis cuando ayude a distinguirlos.', 'Separa elementos con comas o punto y coma según su complejidad.', 'Mantén la oración gramaticalmente completa y paralela.'] }),
  'numbered-lists': verified({ id: 'numbered-lists', label: 'Listas numeradas', manualSection: '6.51', manualPrintedPages: '196', rules: ['Usa números para pasos secuenciales, conclusiones u oraciones completas a las que se hará referencia.', 'Emplea la función automática del procesador y la sangría consistente.', 'Cada elemento completo comienza con mayúscula y termina con puntuación final.', 'No numeres frases sin orden cuando letras o viñetas comuniquen mejor.'] }),
  'bulleted-lists': verified({ id: 'bulleted-lists', label: 'Listas con viñetas', manualSection: '6.52', manualPrintedPages: '196-198', rules: ['Usa viñetas cuando el orden no importa y no se necesita citar elementos por número.', 'Mantén forma gramatical paralela y puntuación consistente.', 'Una lista de oraciones completas lleva mayúscula y punto; una lista de fragmentos integrada a una oración sigue su sintaxis.', 'No mezcles símbolos de viñeta arbitrariamente.'] }),
};

export function getMechanicsRule(id: MechanicsRuleId): Apa7VerifiedMechanicsRule {
  return mechanicsRules[id];
}
