import { z } from 'zod';

export const writingStyleRuleId = z.enum([
  'continuity-flow', 'transitions', 'concision-clarity', 'wordiness-redundancy',
  'sentence-paragraph-length', 'tone', 'colloquialisms', 'jargon',
  'logical-comparisons', 'anthropomorphism', 'verb-tenses', 'active-passive-voice',
  'verb-mood', 'subject-verb-agreement', 'first-third-person-pronouns',
  'editorial-we', 'gender-pronouns', 'relative-pronouns-subject-object',
  'relative-pronouns-subordinate-clauses', 'subordinating-conjunctions',
  'misplaced-dangling-modifiers', 'parallel-construction', 'read-examples',
  'write-from-outline', 'reread-draft', 'peer-help', 'copyeditors-writing-centers',
  'revise-document',
]);

export type WritingStyleRuleId = z.infer<typeof writingStyleRuleId>;

export interface Apa7VerifiedWritingStyleRule {
  id: WritingStyleRuleId;
  label: string;
  manualSection: `4.${number}`;
  manualPrintedPages: string;
  status: 'verified';
  rules: string[];
  citationTreatment: string[];
  referenceTreatment: string[];
  refuseWhen: string[];
}

const verified = (rule: Omit<Apa7VerifiedWritingStyleRule, 'status' | 'citationTreatment' | 'referenceTreatment' | 'refuseWhen'> & Partial<Pick<Apa7VerifiedWritingStyleRule, 'citationTreatment' | 'referenceTreatment' | 'refuseWhen'>>): Apa7VerifiedWritingStyleRule => ({
  ...rule,
  status: 'verified',
  citationTreatment: rule.citationTreatment ?? ['La mejora de estilo no elimina, añade ni cambia por sí sola una cita; conserva exactamente la atribución y el alcance de la fuente.'],
  referenceTreatment: rule.referenceTreatment ?? ['Una corrección de redacción no crea una referencia; toda obra citada debe conservar su entrada y ninguna entrada debe inventarse.'],
  refuseWhen: rule.refuseWhen ?? ['La reescritura cambiaría el significado, la certeza o el alcance de la afirmación.', 'La edición ocultaría quién produjo una idea o un resultado.', 'Se propone una regla gramatical sin considerar que esta edición está adaptada al español.'],
});

export const writingStyleRules: Record<WritingStyleRuleId, Apa7VerifiedWritingStyleRule> = {
  'continuity-flow': verified({ id: 'continuity-flow', label: 'Continuidad y fluidez', manualSection: '4.1', manualPrintedPages: '111', rules: ['Mantén una secuencia lógica sin inconsistencias, contradicciones, omisiones ni material irrelevante.', 'Usa puntuación y estructura para mostrar relaciones entre ideas y conservar una cadencia legible.', 'Presenta cada idea nueva con el contexto necesario y evita saltos que obliguen al lector a reconstruir el argumento.'] }),
  transitions: verified({ id: 'transitions', label: 'Transiciones', manualSection: '4.2', manualPrintedPages: '111-112', rules: ['Usa pronombres con referente inequívoco y conectores temporales, causales, aditivos o de contraste para hacer explícita la relación entre ideas.', 'No sobrecargues el texto con adverbios introductorios; omítelos o reformúlalos cuando no aporten significado.', 'Comprueba que la transición exprese la relación real, no una causalidad o contraste inexistente.'] }),
  'concision-clarity': verified({ id: 'concision-clarity', label: 'Concisión y claridad', manualSection: '4.3', manualPrintedPages: '112-113', rules: ['Di lo necesario con palabras precisas y comprensibles.', 'Elige cada término por su significado exacto y úsalo de manera consistente.', 'Define términos técnicos desconocidos y evita sinónimos que sugieran diferencias no pretendidas.', 'Usa descriptores actuales, respetuosos y acordes con la forma en que las personas se identifican.'] }),
  'wordiness-redundancy': verified({ id: 'wordiness-redundancy', label: 'Palabrería y redundancia', manualSection: '4.4', manualPrintedPages: '113-114', rules: ['Elimina circunloquios y palabras que repiten el mismo significado.', 'Logra énfasis mediante el orden de la oración, no acumulando expresiones redundantes.', 'Prefiere construcciones directas y voz activa cuando aclaren quién realiza la acción.', 'No recortes palabras indispensables para precisión, cautela o atribución.'] }),
  'sentence-paragraph-length': verified({ id: 'sentence-paragraph-length', label: 'Longitud de oraciones y párrafos', manualSection: '4.5', manualPrintedPages: '114', rules: ['APA no fija una longitud mínima o máxima universal para las oraciones.', 'Varía la longitud: demasiadas oraciones breves producen prosa entrecortada y demasiadas oraciones largas dificultan la comprensión.', 'Desarrolla una idea principal coherente por párrafo y divide párrafos excesivamente densos.', 'No fragmentes el texto hasta perder conexiones lógicas.'] }),
  tone: verified({ id: 'tone', label: 'Tono', manualSection: '4.6', manualPrintedPages: '114-115', rules: ['Usa un tono profesional, directo, claro y convincente adecuado al público.', 'Presenta desacuerdos académicos de manera respetuosa y no combativa.', 'Evita recursos literarios que introduzcan ambigüedad, distracción o cambios bruscos.', 'Emplea metáforas con moderación y evita clichés, rimas o efectos que oculten las ideas.'] }),
  colloquialisms: verified({ id: 'colloquialisms', label: 'Coloquialismos', manualSection: '4.7', manualPrintedPages: '115', rules: ['Evita expresiones informales, regionales o vagas cuya interpretación cambie entre lectores.', 'Sustituye aproximaciones como “casi todos” o “muy pocos” por cantidades o descripciones verificables cuando los datos lo permitan.', 'No atribuyas una precisión numérica que los datos originales no poseen.'] }),
  jargon: verified({ id: 'jargon', label: 'Jerga', manualSection: '4.8', manualPrintedPages: '115-116', rules: ['Limita la terminología especializada a la necesaria para comunicar con precisión.', 'Define la jerga cuando lectores ajenos al subcampo puedan no conocerla.', 'No uses tecnicismos como eufemismos ni para dar apariencia de rigor.', 'Conserva el término técnico cuando reemplazarlo alteraría el constructo.'] }),
  'logical-comparisons': verified({ id: 'logical-comparisons', label: 'Comparaciones lógicas', manualSection: '4.9', manualPrintedPages: '116', rules: ['Compara elementos equivalentes y expresa ambos lados de la comparación.', 'Evita comparaciones ambiguas, imposibles o con un referente omitido.', 'Añade “que”, “como” u otra estructura completa cuando la brevedad produzca un falso paralelismo.', 'No transforme correlaciones en comparaciones causales.'] }),
  anthropomorphism: verified({ id: 'anthropomorphism', label: 'Antropomorfismo', manualSection: '4.10', manualPrintedPages: '116-117', rules: ['No atribuyas intenciones o acciones exclusivamente humanas a objetos o conceptos cuando confunda al lector.', 'Empareja acciones humanas con actores humanos, especialmente decisiones e interpretaciones.', 'Son aceptables usos convencionales claros como “los resultados sugieren” o “el capítulo aborda”.', 'No corrijas mecánicamente todo sujeto inanimado: evalúa si existe ambigüedad real.'] }),
  'verb-tenses': verified({ id: 'verb-tenses', label: 'Tiempos verbales', manualSection: '4.11', manualPrintedPages: '117', rules: ['Usa pasado para acciones completadas y resultados observados en un momento definido.', 'Usa antepresente para acciones pasadas sin momento definido o que continúan hasta el presente.', 'Usa presente para conclusiones actuales, contenido estable del escrito y afirmaciones generales apropiadas.', 'Mantén el tiempo verbal consistente y cambia solo cuando cambie realmente el marco temporal.'], citationTreatment: ['El tiempo verbal de una cita narrativa debe representar con precisión la relación con la obra: “informó” para un resultado pasado y “sostiene” solo cuando la afirmación sigue presentándose como actual.'] }),
  'active-passive-voice': verified({ id: 'active-passive-voice', label: 'Voz activa y pasiva', manualSection: '4.12', manualPrintedPages: '117-118', rules: ['Prefiere la voz activa cuando sea importante saber quién realizó la acción.', 'La voz pasiva es válida cuando el foco legítimo sea el objeto o receptor de la acción.', 'No omitas al actor si esa omisión impide evaluar responsabilidad, procedimiento o sesgo.', 'APA permite ambas voces; no afirmes que la pasiva está prohibida.'] }),
  'verb-mood': verified({ id: 'verb-mood', label: 'Modo verbal', manualSection: '4.13', manualPrintedPages: '118', rules: ['Usa indicativo para afirmaciones que presentas como hechos o resultados.', 'Reserva subjuntivo para condiciones contrarias a los hechos, deseadas o improbables según la gramática española.', 'Usa el condicional para hipótesis o consecuencias condicionadas, no para debilitar sin motivo una afirmación verificable.', 'Calibra el grado de certeza con evidencia, no con fórmulas automáticas.'] }),
  'subject-verb-agreement': verified({ id: 'subject-verb-agreement', label: 'Concordancia entre sujeto y verbo', manualSection: '4.14', manualPrintedPages: '118-119', rules: ['Haz concordar verbo y sujeto en número y persona, incluso cuando haya frases interpuestas.', 'Decide singular o plural de sustantivos colectivos según si la acción corresponde al grupo como unidad o a sus miembros.', 'En español, “ninguno” suele concordar en singular aunque lleve complemento plural.', 'Con sujetos coordinados, aplica la concordancia gramatical que corresponda a la construcción completa.'] }),
  'first-third-person-pronouns': verified({ id: 'first-third-person-pronouns', label: 'Primera persona frente a tercera persona', manualSection: '4.15', manualPrintedPages: '119-120', rules: ['Usa primera persona para describir acciones realizadas por el autor o los autores y evitar ambigüedad.', 'No te denomines “el autor” ni sustituyas sistemáticamente “yo” o “nosotros” por tercera persona.', 'Usa “nosotros” solo cuando incluya realmente a todos los autores o al grupo previamente definido.', 'No cambies la autoría o responsabilidad al editar la persona gramatical.'] }),
  'editorial-we': verified({ id: 'editorial-we', label: '“Nosotros” editorial', manualSection: '4.16', manualPrintedPages: '120', rules: ['No uses “nosotros” para significar vagamente la humanidad, la comunidad científica o el lector.', 'Sustitúyelo por un sustantivo preciso, como participantes, investigadores o personas, o define el referente.', 'Puede usarse después de establecer inequívocamente el grupo al que se refiere.'] }),
  'gender-pronouns': verified({ id: 'gender-pronouns', label: 'Problemas de género en pronombres', manualSection: '4.17', manualPrintedPages: '120-121', rules: ['Usa el nombre y los pronombres que la persona emplea para sí misma.', 'Cuando el género sea desconocido o irrelevante, prefiere una construcción neutral o plural que no presuponga masculino.', 'No inventes género, identidad ni pronombres a partir de nombre, apariencia o rol.', 'Sigue la gramática y las preferencias lingüísticas vigentes del contexto en español sin borrar la identidad declarada.'] }),
  'relative-pronouns-subject-object': verified({ id: 'relative-pronouns-subject-object', label: 'Pronombres relativos como sujetos y objetos', manualSection: '4.18', manualPrintedPages: '121', rules: ['Asegura que cada relativo tenga antecedente claro y cumpla la función correcta.', 'Usa “que” para personas o cosas cuando corresponda y las formas compuestas con artículo o preposición según la función.', 'Cuando el relativo sea objeto indirecto o complemento, conserva la preposición exigida.', 'Para personas, “quien” o “quienes” puede seguir a una preposición cuando la construcción lo permita.'] }),
  'relative-pronouns-subordinate-clauses': verified({ id: 'relative-pronouns-subordinate-clauses', label: 'Pronombres relativos en oraciones subordinadas', manualSection: '4.19', manualPrintedPages: '121-122', rules: ['Distingue subordinadas especificativas, necesarias para identificar el antecedente, de explicativas, que añaden información.', 'Encierra entre comas las explicativas y no las especificativas.', 'Elige “que”, formas con artículo, “cual” o “quien” según antecedente, preposición y función.', 'Comprueba que la puntuación no cambie qué personas u objetos abarca la afirmación.'] }),
  'subordinating-conjunctions': verified({ id: 'subordinating-conjunctions', label: 'Conjunciones subordinadas', manualSection: '4.20', manualPrintedPages: '122-123', rules: ['Selecciona la conjunción que expresa la relación real de tiempo, causa, contraste o condición.', 'Reserva “mientras” y “desde” para relaciones temporales cuando otro conector evite ambigüedad.', 'No uses “ya que” o “porque” si solo existe simultaneidad o contraste.', 'Revisa que la subordinación no altere el alcance de una cita.'] }),
  'misplaced-dangling-modifiers': verified({ id: 'misplaced-dangling-modifiers', label: 'Modificadores perdidos o colgantes', manualSection: '4.21', manualPrintedPages: '123-124', rules: ['Coloca adjetivos, adverbios y frases modificadoras junto a la palabra que modifican.', 'Reescribe una frase introductoria colgante para que su sujeto sea quien realiza la acción.', 'Ubica “solo” inmediatamente antes del elemento cuyo alcance limita.', 'No dejes que una corrección gramatical cambie el actor o la condición reportada.'] }),
  'parallel-construction': verified({ id: 'parallel-construction', label: 'Construcción paralela', manualSection: '4.22', manualPrintedPages: '124-125', rules: ['Presenta ideas equivalentes con estructuras sintácticas y conceptuales equivalentes.', 'Mantén completos ambos lados de conjunciones y pares coordinados.', 'Usa construcción paralela en series, listas, comparaciones y encabezados equivalentes.', 'No fuerces paralelismo entre elementos que cumplen funciones distintas.'] }),
  'read-examples': verified({ id: 'read-examples', label: 'Leer para aprender mediante ejemplos', manualSection: '4.23', manualPrintedPages: '125', rules: ['Examina ejemplos sólidos del mismo género para aprender organización y presentación.', 'Usa los ejemplos como modelos de decisiones retóricas, no como texto para copiar.', 'Contrasta el modelo con la consigna actual y con APA 7.'], citationTreatment: ['Cita cualquier idea, frase, estructura original reconocible, tabla o dato que se tome del ejemplo; imitar una convención general no autoriza copiar contenido.'], referenceTreatment: ['Referencia la obra si fue citada o reutilizada; leerla solo como ejemplo no justifica añadirla a la lista.'] }),
  'write-from-outline': verified({ id: 'write-from-outline', label: 'Escribir a partir de un esquema', manualSection: '4.24', manualPrintedPages: '125-126', rules: ['Construye un esquema para ordenar ideas principales y subordinadas y detectar omisiones o digresiones.', 'Relaciona el esquema con los niveles de encabezado finales sin numerarlos automáticamente como si fueran el manuscrito.', 'Actualiza el esquema cuando cambie el argumento y comprueba que cada sección cumpla una función.'] }),
  'reread-draft': verified({ id: 'reread-draft', label: 'Releer el borrador', manualSection: '4.25', manualPrintedPages: '126', rules: ['Deja reposar el borrador y reléelo con una perspectiva nueva.', 'Lee en voz alta para detectar errores, tono y fluidez.', 'Revisa secciones en orden inverso para comprobar que cada argumento esté sustentado.', 'Reserva tiempo suficiente para más de una pasada.'] }),
  'peer-help': verified({ id: 'peer-help', label: 'Buscar ayuda de colegas', manualSection: '4.26', manualPrintedPages: '126', rules: ['Solicita revisión crítica a colegas capaces de evaluar claridad y lógica.', 'Considera más de una lectura independiente cuando sea posible.', 'Los estudiantes pueden pedir comentarios a docente y compañeros dentro de las reglas del curso.', 'Conserva responsabilidad sobre el contenido y documenta contribuciones que alcancen criterios de autoría o agradecimiento.'] }),
  'copyeditors-writing-centers': verified({ id: 'copyeditors-writing-centers', label: 'Correctores y centros de redacción', manualSection: '4.27', manualPrintedPages: '126-127', rules: ['Puede recurrirse a corrección o tutoría para idioma, organización y presentación.', 'Comprueba primero la política de integridad académica del curso o institución.', 'La asistencia editorial no debe fabricar contenido, análisis, citas ni referencias.', 'Reconoce o declara la ayuda cuando la política o el tipo de contribución lo requiera.'], refuseWhen: ['La política del curso prohíbe el tipo de asistencia solicitado.', 'La revisión sustituiría el trabajo intelectual exigido al estudiante.', 'Se pide crear fuentes, datos o resultados inexistentes.'] }),
  'revise-document': verified({ id: 'revise-document', label: 'Revisión integral del documento', manualSection: '4.28', manualPrintedPages: '126-128', rules: ['Revisa primero estructura, lógica y completitud; después párrafos, oraciones, palabras y aspectos mecánicos.', 'Verifica por separado exactitud, consistencia, gramática, ortografía y formato.', 'Los correctores automáticos ayudan, pero no son infalibles.', 'Consulta autoridades lingüísticas confiables para el español cuando el manual no resuelva una duda.', 'Termina comprobando correspondencia entre citas y referencias y que ningún cambio haya alterado datos o atribución.'] }),
};

export function getWritingStyleRule(id: WritingStyleRuleId): Apa7VerifiedWritingStyleRule {
  return writingStyleRules[id];
}
