import { z } from 'zod';

export const publicationRuleId = z.enum([
  'thesis-to-article', 'journal-selection', 'journal-prioritization',
  'predatory-journals', 'editorial-publication-process', 'editors-role',
  'peer-review-process', 'manuscript-decisions', 'manuscript-submission-preparation',
  'online-submission-portal', 'cover-letter', 'publication-correspondence',
  'ethical-certification', 'reprint-adaptation-guidelines',
  'copyright-attribution-required', 'copyright-status', 'permission-fair-use',
  'copyright-attribution-formats', 'article-proofs', 'published-article-copyright',
  'open-access-deposit', 'correction-notice', 'share-article-online',
  'promote-article',
]);

export type PublicationRuleId = z.infer<typeof publicationRuleId>;

export interface Apa7VerifiedPublicationRule {
  id: PublicationRuleId;
  label: string;
  manualSection: `12.${number}`;
  manualPrintedPages: string;
  status: 'verified';
  rules: string[];
  citationTreatment: string[];
  referenceTreatment: string[];
  permissionTreatment: string[];
  refuseWhen: string[];
}

const verified = (rule: Omit<Apa7VerifiedPublicationRule, 'status' | 'citationTreatment' | 'referenceTreatment' | 'permissionTreatment' | 'refuseWhen'> & Partial<Pick<Apa7VerifiedPublicationRule, 'citationTreatment' | 'referenceTreatment' | 'permissionTreatment' | 'refuseWhen'>>): Apa7VerifiedPublicationRule => ({
  ...rule,
  status: 'verified',
  citationTreatment: rule.citationTreatment ?? ['Este paso editorial no modifica el sistema autor-fecha; conserva todas las citas necesarias y su alcance.'],
  referenceTreatment: rule.referenceTreatment ?? ['Este paso editorial no crea referencias por sí mismo; conserva la correspondencia entre citas y lista de referencias.'],
  permissionTreatment: rule.permissionTreatment ?? ['Cumple además las políticas de la revista, institución, contrato, licencia y jurisdicción aplicables.'],
  refuseWhen: rule.refuseWhen ?? ['No se verificó la política vigente de la revista, editorial, repositorio o institución.', 'Se pretende presentar, reutilizar o compartir contenido sin conocer titularidad, licencia o autorización.', 'Se intenta inventar una aceptación, revisión, permiso, licencia, DOI o estado editorial.'],
});

export const publicationRules: Record<PublicationRuleId, Apa7VerifiedPublicationRule> = {
  'thesis-to-article': verified({ id: 'thesis-to-article', label: 'Adaptación de una tesis a artículo', manualSection: '12.1', manualPrintedPages: '381-383', rules: ['Transforma la tesis en un artículo enfocado y autosuficiente; no la reduzcas mediante copia mecánica.', 'Selecciona la pregunta, análisis y evidencia compatibles con el alcance de la revista.', 'Declara en la nota del autor o lugar exigido que el artículo se basa en una tesis o disertación y cita trabajos previos relacionados.', 'Coordina autoría con quienes cumplan criterios de contribución y no asumas que asesoría equivale automáticamente a coautoría.', 'Verifica la política del repositorio y la revista sobre publicación previa.'], citationTreatment: ['Cita la tesis cuando el artículo se apoya en contenido recuperable de ella y la transparencia lo requiere; no te autocites para cada frase reformulada si la relación se declara adecuadamente.', 'Cita otros informes derivados del mismo conjunto de datos para evitar fragmentación o duplicación opaca.'], referenceTreatment: ['Incluye la referencia completa de la tesis o de reportes relacionados cuando se citen.', 'Una tesis alojada en repositorio se referencia según el caso de tesis publicada; una no publicada usa la plantilla correspondiente.'], permissionTreatment: ['Verifica derechos de tablas, figuras, instrumentos y material de terceros que pasan de la tesis al artículo.'] }),
  'journal-selection': verified({ id: 'journal-selection', label: 'Selección de una revista', manualSection: '12.2', manualPrintedPages: '383-384', rules: ['Elige una revista cuyo alcance, lectores, tipos de artículo y métodos coincidan con el manuscrito.', 'Lee artículos recientes e instrucciones vigentes para autores.', 'Comprueba revisión por pares, indexación, costos, acceso, plazos y políticas éticas.', 'No envíes el mismo manuscrito simultáneamente a más de una revista salvo permiso explícito.'], permissionTreatment: ['Las instrucciones de la revista pueden imponer requisitos de permisos antes del envío.'] }),
  'journal-prioritization': verified({ id: 'journal-prioritization', label: 'Priorización de revistas potenciales', manualSection: '12.3', manualPrintedPages: '384', rules: ['Ordena opciones por ajuste científico y público antes que por una sola métrica.', 'Compara alcance, formato, datos abiertos, costos, tiempos, licencia y probabilidad razonable de adecuación.', 'Prepara alternativas sin presentar simultáneamente.', 'No garantices aceptación a partir de métricas o experiencias ajenas.'] }),
  'predatory-journals': verified({ id: 'predatory-journals', label: 'Evitar revistas depredadoras', manualSection: '12.4', manualPrintedPages: '384-386', rules: ['Verifica identidad editorial, comité, revisión, dirección, políticas, indexación, costos y archivo permanente.', 'Desconfía de invitaciones masivas, aceptación garantizada, revisión irrealmente rápida, métricas inventadas y datos de contacto opacos.', 'Evalúa varias señales; una característica aislada no basta para calificar una revista.', 'No confunda acceso abierto legítimo con publicación depredadora.'], citationTreatment: ['Si afirmas que una revista es depredadora, sustenta la afirmación con evidencia verificable y evita acusaciones categóricas no comprobadas.'], referenceTreatment: ['Referencia la política, registro o fuente utilizada si se discute formalmente la legitimidad de la revista.'], refuseWhen: ['No hay evidencia suficiente para evaluar la revista.', 'Solo se cuenta con una opinión, lista desactualizada o ausencia en una base.', 'Se pretende acusar públicamente sin documentación verificable.'] }),
  'editorial-publication-process': verified({ id: 'editorial-publication-process', label: 'Proceso de publicación editorial', manualSection: '12.5', manualPrintedPages: '386', rules: ['El proceso normalmente comprende revisión inicial, revisión por pares, decisión, revisión del manuscrito, producción y publicación.', 'Los plazos y rondas varían; consulta la revista y no inventes fechas.', 'Mantén registro de versión, correspondencia, archivos y decisiones.', 'Una presentación no implica aceptación ni publicación.'] }),
  'editors-role': verified({ id: 'editors-role', label: 'Papel de los editores', manualSection: '12.6', manualPrintedPages: '386-388', rules: ['El editor evalúa adecuación, calidad, ética y recomendaciones de revisores y toma o coordina decisiones.', 'La decisión editorial puede ocurrir antes de revisión externa cuando el manuscrito no encaja.', 'Respeta confidencialidad y canales formales; no contactes revisores ni intentes influir fuera del proceso.', 'Revela conflictos pertinentes.'] }),
  'peer-review-process': verified({ id: 'peer-review-process', label: 'Proceso de revisión por pares', manualSection: '12.7', manualPrintedPages: '388-389', rules: ['La revisión evalúa el manuscrito y formula recomendaciones; no garantiza ausencia de errores.', 'El modelo puede ser simple ciego, doble ciego, abierto u otro; prepara archivos según la política.', 'Responde a cada comentario con respeto, evidencia y ubicación de cambios.', 'Puedes discrepar explicando con claridad; no atribuyas a los revisores afirmaciones que no hicieron.'], citationTreatment: ['Una idea específica de un revisor que se incorpora puede requerir reconocimiento según la política, pero los comentarios confidenciales no se convierten automáticamente en una referencia recuperable.'], referenceTreatment: ['Los informes confidenciales de revisión normalmente no se incluyen en la lista de referencias; una revisión publicada sí se referencia como obra recuperable.'] }),
  'manuscript-decisions': verified({ id: 'manuscript-decisions', label: 'Decisiones sobre manuscritos', manualSection: '12.8', manualPrintedPages: '389-391', rules: ['Distingue rechazo, revisión y nueva presentación, aceptación condicionada y aceptación final según la comunicación real.', 'Una invitación a revisar no es aceptación.', 'Antes de reenviar, prepara versión limpia, versión con cambios si se pide y carta de respuesta punto por punto.', 'No omitas cambios sustantivos ni afirmes que se atendió un comentario si no ocurrió.'] }),
  'manuscript-submission-preparation': verified({ id: 'manuscript-submission-preparation', label: 'Preparación del manuscrito para presentación', manualSection: '12.9', manualPrintedPages: '391', rules: ['Sigue la lista de verificación e instrucciones vigentes de la revista.', 'Retira información identificadora cuando la revisión sea anónima y prepara archivos, tablas, figuras y suplementos en formatos solicitados.', 'Verifica metadatos, citas, referencias, permisos, declaraciones y calidad de figuras.', 'Conserva una copia exacta de la versión enviada.'] }),
  'online-submission-portal': verified({ id: 'online-submission-portal', label: 'Portal de presentación en línea', manualSection: '12.10', manualPrintedPages: '391-392', rules: ['Completa metadatos del portal exactamente y comprueba orden de autoría, afiliaciones, ORCID, título, resumen y archivos.', 'No asumas que el portal extrae correctamente la información del documento.', 'Revisa el PDF generado por el sistema antes de confirmar.', 'Guarda identificador y comprobante del envío.'], referenceTreatment: ['Los metadatos ingresados en el portal no sustituyen la lista de referencias del manuscrito.'] }),
  'cover-letter': verified({ id: 'cover-letter', label: 'Carta de presentación', manualSection: '12.11', manualPrintedPages: '392-393', rules: ['Identifica manuscrito, tipo de artículo, ajuste a la revista y declaraciones exigidas.', 'Confirma originalidad, ausencia de envío simultáneo y aprobación de autores cuando sea verdadero.', 'Declara trabajos relacionados, preprints, conflictos y comunicaciones previas pertinentes.', 'No exageres novedad ni ocultes publicación o datos solapados.'], citationTreatment: ['La carta normalmente no replica la bibliografía; identifica trabajos relacionados de forma suficiente y remite al manuscrito cuando están citados.'] }),
  'publication-correspondence': verified({ id: 'publication-correspondence', label: 'Correspondencia durante la publicación', manualSection: '12.12', manualPrintedPages: '393', rules: ['Usa comunicación profesional, concisa y vinculada al número de manuscrito.', 'Responde dentro del plazo o solicita extensión antes de vencer.', 'Conserva correspondencia y acuerdos relevantes.', 'No interpretes silencio como aceptación, permiso o cambio de política.'], referenceTreatment: ['La correspondencia privada normalmente no es una referencia recuperable; si se cita por necesidad, usa comunicación personal en el texto.'] }),
  'ethical-certification': verified({ id: 'ethical-certification', label: 'Certificación de requisitos éticos', manualSection: '12.13', manualPrintedPages: '393-394', rules: ['Certifica solamente aprobación, consentimiento, autoría, conflictos, originalidad, datos y permisos que puedan documentarse.', 'Todos los autores deben conocer y aprobar la versión enviada y asumir responsabilidad según su contribución.', 'Declara publicación duplicada, datos reutilizados, registro, financiación y conflictos cuando corresponda.', 'No uses una casilla del portal como sustituto de obtener aprobación o permiso.'], citationTreatment: ['Las declaraciones éticas no sustituyen las citas de datos, métodos y obras reutilizadas.'], permissionTreatment: ['Conserva comprobantes de aprobación ética y permisos; no fabriques identificadores ni cartas.'], refuseWhen: ['No existe evidencia de la certificación solicitada.', 'Una persona no aprobó autoría o versión final.', 'Se pide marcar como cumplido un requisito todavía pendiente.'] }),
  'reprint-adaptation-guidelines': verified({ id: 'reprint-adaptation-guidelines', label: 'Reimpresión o adaptación de material', manualSection: '12.14', manualPrintedPages: '394-395', rules: ['Determina si el material es propio, reproducido sin cambios o adaptado.', 'Identifica obra original, titular, licencia, cantidad y finalidad de uso.', 'Incluye cita, referencia y atribución de derechos apropiadas; son obligaciones distintas.', 'Obtén permiso cuando la licencia, dominio público o excepción aplicable no cubra el uso.', 'Aplica también a material propio publicado previamente.'], citationTreatment: ['Cita la obra original cuando se discuta o reutilice su contenido; una nota de derechos no sustituye la cita autor-fecha cuando esta corresponde.'], referenceTreatment: ['Incluye la entrada completa de la obra original según su tipo real.'], permissionTreatment: ['Citar no concede permiso y adaptar no elimina automáticamente los derechos de la obra original.'], refuseWhen: ['No se conoce la fuente o titular original.', 'Se afirma que estar en internet equivale a libre uso.', 'No se distinguió reproducción, adaptación y creación propia.'] }),
  'copyright-attribution-required': verified({ id: 'copyright-attribution-required', label: 'Material que requiere atribución de derechos de autor', manualSection: '12.15', manualPrintedPages: '395-396', rules: ['Evalúa tablas, figuras, fotografías, ilustraciones, ítems de pruebas, escalas, cuestionarios, poemas, letras, citas extensas y otros materiales protegidos.', 'La cantidad permitida depende de la obra, licencia, finalidad y jurisdicción; no existe un umbral APA universal que autorice todo uso.', 'Una paráfrasis de ideas sigue requiriendo cita aunque no reproduzca la expresión protegida.', 'Protege además privacidad y consentimiento cuando el material identifica personas.'], citationTreatment: ['Todo material ajeno lleva atribución académica; la cita textual usa localizador verificable.'], referenceTreatment: ['La fuente recuperable aparece en referencias incluso cuando también existe una nota de derechos.'], permissionTreatment: ['Obtén autorización separada cuando el uso exceda licencia, dominio público o excepción legal aplicable.'] }),
  'copyright-status': verified({ id: 'copyright-status', label: 'Estado de los derechos de autor', manualSection: '12.16', manualPrintedPages: '396-397', rules: ['Determina autoría/titularidad, fecha, jurisdicción, licencia, duración, cesiones y versión del material.', 'Distingue material protegido, dominio público, licencia abierta y permiso específico.', 'Una licencia abierta conserva condiciones de atribución, versión, enlace y cambios.', 'No presupongas que ausencia de aviso de copyright significa dominio público.'], citationTreatment: ['Dominio público y licencia abierta no eliminan la atribución académica de una idea u obra utilizada.'], referenceTreatment: ['Referencia la obra normalmente y añade información de licencia cuando la plantilla o reutilización lo requiera.'], permissionTreatment: ['Conserva evidencia del estado o licencia comprobados en la fecha de uso.'] }),
  'permission-fair-use': verified({ id: 'permission-fair-use', label: 'Permiso y uso justo', manualSection: '12.17', manualPrintedPages: '397-399', rules: ['El “fair use” explicado por APA pertenece al derecho estadounidense y no debe trasladarse automáticamente a Perú u otra jurisdicción.', 'Evalúa propósito, naturaleza de la obra, cantidad/sustancialidad y efecto en el mercado cuando esa doctrina sea aplicable.', 'La decisión jurídica depende del contexto; APA no concede una autorización.', 'Cuando exista duda material, limita el uso, enlaza o describe en vez de reproducir y consulta a la institución o asesoría competente.'], citationTreatment: ['Una cita correcta no convierte automáticamente la reproducción en uso justo.'], referenceTreatment: ['Una referencia completa tampoco sustituye el permiso.'], permissionTreatment: ['Para Perú verifica la legislación y política institucional vigente; no ofrezcas una conclusión jurídica categórica sin autoridad competente.'], refuseWhen: ['No se identificó jurisdicción, titular o cantidad de material.', 'Se pide garantizar que el uso es legal únicamente porque es educativo.', 'Se confunde atribución APA con autorización.'] }),
  'copyright-attribution-formats': verified({ id: 'copyright-attribution-formats', label: 'Formatos de atribución de derechos de autor', manualSection: '12.18', manualPrintedPages: '399-400', rules: ['Coloca la atribución de una tabla o figura en su nota general y la de otro material en nota al pie o ubicación exigida.', 'Indica si fue reproducido o adaptado, datos de la obra, titular, año y estado de permiso o licencia conforme al caso.', 'Reproduce el texto de atribución exigido por la licencia o permiso cuando exista.', 'No mezcles la atribución de derechos con la referencia bibliográfica ni omitas una de ellas.'], citationTreatment: ['La nota de derechos identifica el origen y condición de reutilización; usa además cita autor-fecha al discutir la obra.'], referenceTreatment: ['Incluye la referencia completa de la fuente original en la lista general.'], permissionTreatment: ['La atribución debe coincidir con la licencia o carta de permiso real; no inventes “usado con permiso”.'] }),
  'article-proofs': verified({ id: 'article-proofs', label: 'Pruebas de preimpresión o galera', manualSection: '12.19', manualPrintedPages: '400-402', rules: ['Revisa pruebas contra el manuscrito aceptado para detectar errores de producción, no para reescribir el estudio.', 'Comprueba autores, afiliaciones, ecuaciones, símbolos, tablas, figuras, notas, citas, referencias, enlaces y suplementos.', 'Responde todas las consultas del editor y limita cambios sustantivos a los autorizados.', 'Conserva registro de correcciones solicitadas.'], citationTreatment: ['Verifica que cada cita siga apuntando a la obra correcta y que los localizadores no se hayan alterado.'], referenceTreatment: ['Comprueba nombres, fechas, títulos, volumen, páginas, DOI y correspondencia bidireccional en la prueba final.'] }),
  'published-article-copyright': verified({ id: 'published-article-copyright', label: 'Derechos de un artículo publicado', manualSection: '12.20', manualPrintedPages: '402-403', rules: ['Lee el contrato para saber qué derechos se transfieren o licencian y qué usos conserva cada autor.', 'Distingue manuscrito enviado, manuscrito aceptado y versión publicada.', 'No distribuyas una versión que la política no permite ni elimines avisos o DOI.', 'Las condiciones pueden variar por revista, financiador y fecha.'], citationTreatment: ['Cita la versión realmente consultada y usa su DOI cuando exista.'], referenceTreatment: ['La referencia apunta normalmente a la versión de registro; una versión archivada puede requerir la URL recuperable adecuada.'], permissionTreatment: ['Verifica contrato y política vigente antes de reutilizar o compartir.'] }),
  'open-access-deposit': verified({ id: 'open-access-deposit', label: 'Depósito de acceso abierto', manualSection: '12.21', manualPrintedPages: '403', rules: ['Comprueba qué versión puede depositarse, repositorio permitido, embargo, licencia y aviso exigido.', 'Satisface políticas de financiador e institución además de la editorial.', 'Añade DOI o enlace a la versión de registro y conserva metadatos completos.', 'No llames acceso abierto a un archivo alojado contra la política aplicable.'], citationTreatment: ['Cita la obra por sus metadatos canónicos aunque se consulte una copia permitida en repositorio.'], referenceTreatment: ['Prefiere DOI; usa URL del repositorio cuando la plantilla y disponibilidad de la obra lo justifiquen.'], permissionTreatment: ['El depósito requiere un derecho o licencia verificable; accesibilidad técnica no equivale a autorización.'] }),
  'correction-notice': verified({ id: 'correction-notice', label: 'Aviso de corrección', manualSection: '12.22', manualPrintedPages: '403-404', rules: ['Solicita corrección cuando un error publicado afecta el registro y describe con precisión qué cambia y qué permanece.', 'Distingue errata/corrección, retractación y actualización; sigue el procedimiento editorial.', 'No modifiques silenciosamente una versión publicada.', 'Evalúa si el error afecta datos, análisis, conclusiones, autoría o transparencia.'], citationTreatment: ['Al citar un artículo corregido, consulta la versión actual y el aviso; cita también la corrección si es relevante para la afirmación.', 'No cites como vigente un resultado retractado o corregido sin advertirlo.'], referenceTreatment: ['Un aviso de corrección recuperable puede llevar su propia entrada como publicación; vincúlalo con el artículo afectado.'], permissionTreatment: ['La corrección no cambia por sí sola la licencia o titularidad del artículo.'] }),
  'share-article-online': verified({ id: 'share-article-online', label: 'Compartir el artículo en línea', manualSection: '12.23', manualPrintedPages: '404-405', rules: ['Comparte enlaces persistentes o versiones autorizadas conforme al contrato y la política editorial.', 'Identifica claramente preprint, manuscrito aceptado y versión de registro.', 'No subas archivos de terceros, suplementos sensibles o versiones no autorizadas.', 'Conserva DOI y aviso de cita recomendado.'], citationTreatment: ['Compartir un enlace no sustituye cómo debe citarse el artículo en un trabajo.'], referenceTreatment: ['La referencia usa los metadatos del artículo, no el texto promocional de la publicación en redes.'], permissionTreatment: ['Verifica versión y canal permitidos antes de subir el archivo.'] }),
  'promote-article': verified({ id: 'promote-article', label: 'Promoción del artículo', manualSection: '12.24', manualPrintedPages: '405-406', rules: ['Describe hallazgos con precisión, contexto y limitaciones en comunicaciones públicas.', 'Enlaza al artículo o versión accesible autorizada y proporciona metadatos suficientes.', 'No exageres causalidad, generalización, novedad o certeza para atraer atención.', 'Protege participantes, datos confidenciales y material bajo embargo.'], citationTreatment: ['Una publicación promocional que comunica resultados debe atribuir y enlazar el artículo; en un trabajo académico se cita el artículo, no el anuncio, salvo que el anuncio sea el objeto analizado.'], referenceTreatment: ['Referencia la obra primaria cuando sustenta la afirmación; una publicación en redes se referencia solo si es la fuente efectivamente utilizada.'], permissionTreatment: ['Usa imágenes, fragmentos y archivos únicamente dentro de las licencias y políticas aplicables.'] }),
};

export function getPublicationRule(id: PublicationRuleId): Apa7VerifiedPublicationRule {
  return publicationRules[id];
}
