import { z } from 'zod';

export const referenceRuleId = z.enum([
  'determine-reference-category',
  'web-category-last-resort',
  'online-versus-print',
  'four-reference-elements',
  'reference-punctuation',
  'reference-accuracy-consistency',
  'author-definition',
  'author-element-format',
  'author-name-spelling-capitalization',
  'specialized-author-roles',
  'group-authors',
  'no-author',
  'date-definition',
  'date-element-format',
  'updated-or-reviewed-work-date',
  'retrieval-date',
  'no-date',
  'title-definition',
  'title-element-format',
  'series-and-multivolume-work',
  'bracketed-description',
  'no-title',
  'source-definition',
  'source-element-format',
  'periodical-source',
  'periodical-missing-information',
  'article-number',
  'edited-chapter-source',
  'publisher-source',
  'database-archive-source',
  'specific-location-source',
  'social-media-source',
  'website-source',
  'when-to-include-doi-url',
  'doi-url-format',
  'shortened-doi-url',
  'no-source',
  'other-language-work',
  'translated-work',
  'reprinted-work',
  'republished-reissued-work',
  'religious-classical-work',
  'reference-list-format',
  'reference-list-alphabetical-order',
  'surname-name-order',
  'same-first-author-order',
  'same-author-same-date-order',
  'same-surname-first-authors',
  'no-author-anonymous-order',
  'reference-abbreviations',
  'annotated-bibliography',
  'meta-analysis-references',
]);

export type ReferenceRuleId = z.infer<typeof referenceRuleId>;

export interface Apa7VerifiedReferenceRule {
  id: ReferenceRuleId;
  label: string;
  manualSection: `9.${number}`;
  manualPrintedPages: string;
  status: 'verified';
  whenToUse: string;
  rules: string[];
  citationImpact: string[];
  referencePattern: string;
  refuseWhen: string[];
}

const sharedRefusal = [
  'No se determinó el tipo real de obra antes de escoger la plantilla.',
  'Se inventó o mezcló información bibliográfica de fuentes distintas.',
  'Los datos no se comprobaron en la obra original o en metadatos confiables.',
];

const verified = (rule: Omit<Apa7VerifiedReferenceRule, 'status' | 'refuseWhen'> & { refuseWhen?: string[] }): Apa7VerifiedReferenceRule => ({
  ...rule,
  status: 'verified',
  refuseWhen: rule.refuseWhen ?? sharedRefusal,
});

export const referenceRules: Record<ReferenceRuleId, Apa7VerifiedReferenceRule> = {
  'determine-reference-category': verified({
    id: 'determine-reference-category', label: 'Determinar la categoría de referencia', manualSection: '9.1', manualPrintedPages: '287-288',
    whenToUse: 'Antes de elegir cualquier plantilla de referencia.',
    rules: ['Determina primero el grupo, después la categoría y finalmente el tipo de referencia.', 'Una categoría reúne varios tipos; por ejemplo, publicaciones periódicas incluye revista científica, magazine, periódico y blog.', 'Si no existe un ejemplo idéntico, elige el tipo más parecido y adapta sus cuatro elementos.', 'El modo de acceso o formato —en línea, impreso, PDF, DVD o préstamo— suele tener poca o ninguna repercusión en la categoría.'],
    citationImpact: ['Una vez identificada la autoría y fecha del tipo correcto, aplica la cita autor-fecha correspondiente.', 'No uses el nombre de la plataforma como autor por el solo hecho de haber recuperado allí la obra.'],
    referencePattern: 'Autor. (Fecha). Título. Fuente, ajustado según la categoría y el tipo real de obra.',
  }),
  'web-category-last-resort': verified({
    id: 'web-category-last-resort', label: 'Uso de la categoría páginas y sitios web', manualSection: '9.2', manualPrintedPages: '288',
    whenToUse: 'Cuando una obra se encuentra en un sitio web y debe decidirse si realmente es una página web.',
    rules: ['Pregunta primero qué tipo de obra existe en el sitio.', 'Usa la categoría de páginas/sitios web solo si no encaja mejor en otra categoría.', 'Un informe gubernamental alojado en web sigue siendo informe.', 'Una página informativa de un sitio gubernamental puede ser página web.', 'No confundas “recuperado en línea” con la categoría “página web”.'],
    citationImpact: ['La cita corresponde al autor de la obra, no automáticamente al sitio o plataforma.', 'La cita usa el año aunque la referencia contenga una fecha más específica.'],
    referencePattern: 'Aplica el patrón del tipo real; solo como último recurso: Autor. (Fecha). Título de la página. Sitio si difiere. URL',
    refuseWhen: ['Solo se conoce la URL y no se inspeccionó qué tipo de obra contiene.', 'Se intenta convertir un artículo, libro, informe o conjunto de datos en página web.', 'No se verificaron autor, fecha o título visibles en la propia obra.'],
  }),
  'online-versus-print': verified({
    id: 'online-versus-print', label: 'Referencias en línea e impresas', manualSection: '9.3', manualPrintedPages: '288',
    whenToUse: 'Cuando debe decidirse si el soporte en línea o impreso cambia la referencia.',
    rules: ['Las versiones en línea e impresas usan en gran medida la misma plantilla.', 'Autor, fecha, título y fuente siguen siendo los elementos generales.', 'La diferencia suele aparecer en el elemento fuente: DOI para obras con DOI y URL para muchas obras en línea sin DOI.', 'La mayoría de nombres y URLs de bases de datos se omiten, salvo excepciones expresas.', 'Usa una sola plantilla coherente, no una combinación de varias.'],
    citationImpact: ['La modalidad en línea o impresa no cambia por sí sola la cita autor-fecha.'],
    referencePattern: 'Autor. (Fecha). Título. Fuente. DOI o URL únicamente cuando corresponda.',
  }),
  'four-reference-elements': verified({
    id: 'four-reference-elements', label: 'Cuatro elementos y datos faltantes', manualSection: '9.4', manualPrintedPages: '289-290',
    whenToUse: 'Para construir una referencia o adaptarla cuando falta autor, fecha, título o fuente.',
    rules: ['Autor responde quién; fecha, cuándo; título, cómo se llama; fuente, dónde se recupera.', 'Sin autor, el título pasa a la posición de autor y gobierna la cita.', 'Sin fecha, usa s. f.', 'Sin título, describe la obra entre corchetes.', 'Si faltan varios elementos, aplica conjuntamente esas sustituciones conservando el orden.', 'Si falta la fuente y la obra es irrecuperable, cítala como comunicación personal; de lo contrario busca otra obra recuperable.', 'No sustituyas un dato desconocido con una conjetura.'],
    citationImpact: ['Sin autor: (Título, año) o Título (año).', 'Sin fecha: (Autor, s. f.) o Autor (s. f.).', 'Sin autor ni título: ([Descripción de la obra], año).', 'Una comunicación personal se cita solo en el texto con identidad y fecha exacta.'],
    referencePattern: 'Autor. (Fecha). Título. Fuente. Si falta: Título. (Fecha). Fuente; Autor. (s. f.). Título. Fuente; Autor. (Fecha). [Descripción]. Fuente.',
    refuseWhen: ['Se propone “Anónimo” solo porque falta el autor.', 'Se inventa un año, título o fuente para completar el patrón.', 'La fuente es irrecuperable pero se intenta fabricar una entrada bibliográfica.'],
  }),
  'reference-punctuation': verified({
    id: 'reference-punctuation', label: 'Puntuación en referencias', manualSection: '9.5', manualPrintedPages: '290-291',
    whenToUse: 'Al revisar los límites y partes internas de una entrada.',
    rules: ['En general, coloca punto después de autor, fecha, título y fuente.', 'No coloques punto después de un DOI o URL.', 'Usa comas o paréntesis para separar partes dentro de un mismo elemento.', 'En artículos, usa coma entre apellido e iniciales, entre autores, entre revista y volumen, y entre número de edición y páginas.', 'No pongas coma entre volumen y número: el número va inmediatamente entre paréntesis.', 'La puntuación dentro de un elemento en cursiva también va en cursiva; la puntuación entre elementos no.'],
    citationImpact: ['La puntuación de la referencia no modifica la forma autor-fecha de la cita.'],
    referencePattern: 'Autor. (Fecha). Título. Fuente. URL-sin-punto-final',
  }),
  'reference-accuracy-consistency': verified({
    id: 'reference-accuracy-consistency', label: 'Precisión y consistencia de referencias', manualSection: '9.6', manualPrintedPages: '291',
    whenToUse: 'Antes de entregar o publicar una lista de referencias.',
    rules: ['Compara cada referencia con la publicación original.', 'La persona autora del trabajo es responsable de toda la información de la lista.', 'Edita al estilo APA las citas sugeridas por bases de datos o generadores.', 'Mantén el orden autor, fecha, título y fuente.', 'La consistencia facilita la lectura, recuperación, vinculación e indexación automática.', 'Elementos desordenados o incompletos pueden impedir que los lectores o algoritmos encuentren la obra.'],
    citationImpact: ['Comprueba que autor y año coincidan entre cada cita y su entrada.', 'Una cita sugerida automáticamente no es evidencia de que los metadatos sean correctos.'],
    referencePattern: 'Autor verificado. (Fecha verificada). Título verificado. Fuente recuperable verificada.',
    refuseWhen: ['Solo se dispone de una cita generada automáticamente y no de la obra o metadatos confiables.', 'Autor, fecha, título o fuente no coinciden entre registros.', 'No puede comprobarse que la URL o DOI conduzcan a la obra citada.'],
  }),
  'author-definition': verified({
    id: 'author-definition', label: 'Definición de autor', manualSection: '9.7', manualPrintedPages: '291-292',
    whenToUse: 'Para identificar quién ocupa el elemento autor.',
    rules: ['Autor es la persona o grupo responsable de la obra.', 'Puede ser un individuo, varias personas, un grupo o una combinación.', 'Según el tipo, puede ocupar esa posición una función principal como editor, director, investigador principal o anfitrión.', 'La autoría puede deducirse razonablemente del contexto, portada, créditos, “Acerca de” o reconocimientos.', 'Si no puede determinarse, aplica la regla de obra sin autor.'],
    citationImpact: ['La persona o grupo que ocupa el elemento autor gobierna la cita autor-fecha.', 'No atribuyas automáticamente la cita a una persona mencionada pero no acreditada como responsable.'],
    referencePattern: 'Responsable de la obra. (Fecha). Título. Fuente.',
  }),
  'author-element-format': verified({
    id: 'author-element-format', label: 'Formato del elemento autor', manualSection: '9.8', manualPrintedPages: '292-293',
    whenToUse: 'Para escribir nombres individuales, múltiples, únicos, seudónimos y usuarios.',
    rules: ['Invierte nombres personales: Apellido, A. A.', 'Separa autores con comas y usa & antes del último; con tres o más usa coma serial.', 'Con hasta 20 autores incluye todos.', 'Con 21 o más incluye los primeros 19, puntos suspensivos sin &, y el último.', 'Deja espacio entre iniciales; conserva guiones en nombres y separa sufijos como Jr. o III con coma.', 'Un nombre único, inseparable, seudónimo o usuario se escribe completo sin abreviar.', 'No incluyas títulos, cargos, rangos ni grados académicos.', 'Si se conocen nombre real y usuario, escribe el real invertido o el grupo y luego el usuario entre corchetes, conservando @.', 'Colaboradores acreditados con “con” pueden incluirse entre paréntesis en la referencia, pero la cita usa solo el autor principal.'],
    citationImpact: ['La cita aplica 1, 2 o 3+ autores según 8.17, aunque la referencia pueda mostrar hasta 20.', 'Los colaboradores con “con” no se incluyen en la cita.', 'Nombres únicos y usuarios no se abrevian en la cita.'],
    referencePattern: 'Apellido, A. A., Apellido, B. B., & Apellido, C. C. (Fecha). Título. Fuente.',
    refuseWhen: ['No se confirmó el orden apellido/nombre del autor.', 'Se omitieron autores para acortar una lista de 20 o menos.', 'Se usó et al. dentro de la lista de referencias.'],
  }),
  'author-name-spelling-capitalization': verified({
    id: 'author-name-spelling-capitalization', label: 'Ortografía y mayúsculas en nombres', manualSection: '9.9', manualPrintedPages: '293',
    whenToUse: 'Cuando un apellido compuesto, con guion o con capitalización no convencional puede alterarse.',
    rules: ['Escribe el apellido exactamente como aparece en la obra, incluidos guiones y apellidos de varias partes.', 'Si hay duda, consulta otras obras que lo citen, bases bibliográficas, sitio o CV del autor.', 'Conserva la capitalización preferida por la persona, incluso formas como bell hooks.'],
    citationImpact: ['Conserva la misma ortografía y capitalización en la cita para que coincida con la referencia.'],
    referencePattern: 'Apellido presentado por el autor, Iniciales. (Fecha). Título. Fuente.',
  }),
  'specialized-author-roles': verified({
    id: 'specialized-author-roles', label: 'Funciones especializadas', manualSection: '9.10', manualPrintedPages: '293-294',
    whenToUse: 'Cuando una contribución principal distinta de “autor” ocupa la posición de autor.',
    rules: ['Coloca la función entre paréntesis después del nombre y termina el elemento con punto.', 'Usa (Ed.) para un editor y (Eds.) una sola vez para varios.', 'Si personas diferentes cumplen funciones diferentes, identifica cada función por separado.', 'Si una persona cumple varias, combina las funciones con “y”.', 'Algunas funciones se acreditan más adelante, no en autor, según el tipo de obra.'],
    citationImpact: ['La cita usa los apellidos o el grupo en posición de autor; la etiqueta de función no entra en la cita.'],
    referencePattern: 'Apellido, A. A. (Función). (Fecha). Título. Fuente.',
    refuseWhen: ['Se asignó una función sin revisar el tipo de obra y sus créditos.', 'Una función que pertenece al elemento fuente se movió a autor.', 'Se omitieron funciones distintas realizadas por personas diferentes.'],
  }),
  'group-authors': verified({
    id: 'group-authors', label: 'Autores grupales', manualSection: '9.11', manualPrintedPages: '294-295',
    whenToUse: 'Cuando la responsabilidad pertenece a una organización, agencia, empresa, hospital o grupo de trabajo.',
    rules: ['Escribe el nombre completo del grupo en la referencia y no lo abrevies.', 'En organismos jerárquicos usa normalmente el organismo responsable más específico.', 'Incluye organismos superiores en autor solo cuando hagan falta para diferenciar grupos homónimos; ordena de superior a subdivisión.', 'Un grupo ya incluido como autor no se repite como editorial/fuente.', 'Si la portada acredita solo al grupo, usa autor grupal; si acredita personas, usa autores individuales y coloca el grupo en la fuente cuando corresponda.', 'Los autores sugeridos por una base deben comprobarse y ajustarse.'],
    citationImpact: ['En el texto puede abreviarse un grupo siguiendo 8.21.', 'La abreviatura nunca sustituye el nombre completo de la referencia.'],
    referencePattern: 'Nombre completo del grupo responsable. (Fecha). Título. Fuente si difiere.',
  }),
  'no-author': verified({
    id: 'no-author', label: 'Obra sin autor', manualSection: '9.12', manualPrintedPages: '295',
    whenToUse: 'Cuando la autoría es desconocida o no puede determinarse razonablemente.',
    rules: ['Mueve el título a la posición de autor, seguido de punto, antes de la fecha.', 'Usa Anónimo únicamente si la obra está firmada literalmente así.'],
    citationImpact: ['La cita usa el título y el año; aplica cursivas o comillas según 8.14.', 'Si la obra firma Anónimo, cita (Anónimo, año).'],
    referencePattern: 'Título. (Fecha). Fuente. o Anónimo. (Fecha). Título. Fuente.',
    refuseWhen: ['No se revisaron portada, créditos o contexto para buscar autor.', 'Se sustituyó un autor desconocido por Anónimo.', 'La cita no puede vincularse de forma inequívoca con el título que inicia la referencia.'],
  }),
  'date-definition': verified({
    id: 'date-definition', label: 'Definición de fecha', manualSection: '9.13', manualPrintedPages: '295',
    whenToUse: 'Para identificar la fecha de publicación aplicable a la obra.',
    rules: ['La fecha puede ser año, fecha exacta, año y mes, año y estación, o rango.', 'Para libros usa la fecha de derechos de autor de la edición consultada.', 'Para artículos usa el año del volumen.', 'En páginas web no uses automáticamente el copyright general del pie; debe corresponder al contenido citado.', 'Una fecha de última actualización sirve solo si es atribuible al contenido específico.'],
    citationImpact: ['La cita en el texto normalmente utiliza solo el año de esa fecha.'],
    referencePattern: 'Autor. (Fecha de publicación pertinente). Título. Fuente.',
  }),
  'date-element-format': verified({
    id: 'date-element-format', label: 'Formato del elemento fecha', manualSection: '9.14', manualPrintedPages: '295-296',
    whenToUse: 'Para escribir el nivel de precisión y estado de publicación de la fecha.',
    rules: ['Coloca la fecha entre paréntesis y termina con punto.', 'Usa la fecha más específica exigida por el tipo: año; año y mes; o año, mes y día.', 'En obras inéditas o informales usa el año de producción, no “en proceso” ni “enviado para su publicación” como fecha.', 'Para una obra aceptada no publicada usa “en prensa” sin fecha.', 'Para publicación anticipada usa su año; si ya existe publicación definitiva, usa la fecha definitiva.', 'No inventes día o mes cuando el tipo o la fuente no los proporciona.'],
    citationImpact: ['La cita reproduce el año o “en prensa”, no el mes ni el día.'],
    referencePattern: 'Autor. (Año[, mes día/estación]). Título. Fuente.',
  }),
  'updated-or-reviewed-work-date': verified({
    id: 'updated-or-reviewed-work-date', label: 'Obra en línea actualizada o revisada', manualSection: '9.15', manualPrintedPages: '296',
    whenToUse: 'Cuando una fuente en línea muestra fecha de actualización o revisión.',
    rules: ['Usa la fecha de actualización si está disponible y corresponde claramente al contenido específico.', 'No uses una fecha de revisión general si el contenido citado no necesariamente cambió.', 'Ignora fechas de revisión irrelevantes para la obra concreta.'],
    citationImpact: ['La cita usa el año de la actualización aplicable.'],
    referencePattern: 'Autor. (Fecha de actualización aplicable). Título. Fuente.',
    refuseWhen: ['La fecha pertenece al sitio general y no a la página citada.', 'No puede determinarse si “revisado” implicó actualización del contenido.', 'Se sustituyó una fecha de publicación verificable por una marca técnica del sitio.'],
  }),
  'retrieval-date': verified({
    id: 'retrieval-date', label: 'Fecha de recuperación', manualSection: '9.16', manualPrintedPages: '296-297',
    whenToUse: 'Cuando una obra no archivada está diseñada o destinada a cambiar con el tiempo.',
    rules: ['La mayoría de referencias no lleva fecha de recuperación.', 'Inclúyela para obras inestables/no archivadas que probablemente cambien.', 'No la incluyas si existen versiones estables archivadas o enlaces permanentes, como revisiones archivadas de Wikipedia o Cochrane.', 'La fecha de recuperación aparece en el elemento fuente antes de la URL.'],
    citationImpact: ['La fecha de recuperación no aparece en la cita; la cita usa la fecha de publicación o s. f.'],
    referencePattern: 'Autor. (Fecha o s. f.). Título. Fuente. Recuperado el día de mes de año, de URL',
    refuseWhen: ['No se verificó que la obra cambie y carezca de archivo estable.', 'Se agrega fecha de recuperación a toda fuente en línea.', 'Se inventa la fecha en que el estudiante consultó la obra.'],
  }),
  'no-date': verified({
    id: 'no-date', label: 'Obra sin fecha', manualSection: '9.17', manualPrintedPages: '297',
    whenToUse: 'Cuando la fecha de publicación es desconocida o no puede determinarse.',
    rules: ['Escribe s. f. entre paréntesis, con punto tras cada letra y sin espacio entre ellas.', 'No confundas falta de fecha con fecha de recuperación.'],
    citationImpact: ['Usa (Autor, s. f.) o Autor (s. f.).'],
    referencePattern: 'Autor. (s. f.). Título. Fuente.',
    refuseWhen: ['No se revisaron fecha de publicación, actualización o revisión del contenido.', 'Se reemplaza una fecha ausente por la fecha de acceso.', 'Se inventa un año aproximado sin indicación explícita de circa.'],
  }),
  'title-definition': verified({
    id: 'title-definition', label: 'Definición de título', manualSection: '9.18', manualPrintedPages: '297',
    whenToUse: 'Para distinguir el título de la obra del título del contenedor.',
    rules: ['El título es el nombre de la obra citada.', 'En una obra independiente, su título ocupa el elemento título.', 'En una obra que forma parte de un todo, el título de la parte ocupa título y el título del contenedor aparece en fuente.'],
    citationImpact: ['El título gobierna la cita solo cuando falta autor.'],
    referencePattern: 'Autor. (Fecha). Título de la obra o parte. Título del contenedor/fuente.',
  }),
  'title-element-format': verified({
    id: 'title-element-format', label: 'Formato del elemento título', manualSection: '9.19', manualPrintedPages: '297-298',
    whenToUse: 'Para decidir cursiva, mayúsculas y datos adicionales del título.',
    rules: ['Una parte de un todo, como artículo o capítulo, no lleva cursiva ni comillas.', 'Una obra independiente, como libro, informe o página web, lleva título en cursiva.', 'En ambos casos usa estilo oración: mayúscula inicial y nombres propios.', 'En libros e informes, información identificadora como edición, reporte o volumen va entre paréntesis tras el título, sin cursiva y sin punto intermedio.', 'Si edición y volumen aparecen juntos, sepáralos con coma y coloca primero la edición.', 'Un volumen numerado con título propio integra número y título en el título principal.', 'Termina con punto, salvo que ya termine en ? o !.'],
    citationImpact: ['Si falta autor, conserva en la cita la cursiva para obra independiente o usa comillas para parte de un todo.'],
    referencePattern: 'Autor. (Fecha). Título en estilo oración (edición, volumen). Fuente.',
  }),
  'series-and-multivolume-work': verified({
    id: 'series-and-multivolume-work', label: 'Series y obras de varios volúmenes', manualSection: '9.20', manualPrintedPages: '298',
    whenToUse: 'Cuando un libro pertenece a una obra multivolumen o a una serie relacionada.',
    rules: ['En una verdadera obra de varios volúmenes, incluye el título de la serie/obra completa según el patrón del volumen.', 'En una serie de libros independientes y relacionados, incluye solo el título del libro, no el nombre de la serie.', 'Si el nombre de una serie independiente puede confundirse o es difícil de encontrar, omítelo.'],
    citationImpact: ['La cita usa el autor y año de la obra o volumen consultado.'],
    referencePattern: 'Autor. (Fecha). Título del volumen: Título específico (Vol. x). Editorial.',
  }),
  'bracketed-description': verified({
    id: 'bracketed-description', label: 'Descripciones entre corchetes', manualSection: '9.21', manualPrintedPages: '298',
    whenToUse: 'Cuando el tipo o formato de una obra necesita identificarse para poder recuperarla.',
    rules: ['Coloca una descripción breve entre corchetes después del título y antes del punto.', 'Se usa especialmente fuera de artículos/libros/reportes: audiovisual, software, datos, literatura gris, manuscritos, tesis y redes sociales.', 'La descripción inicia con mayúscula y no va en cursiva.', 'Los corchetes consecutivos son aceptables cuando cumplen funciones diferentes.', 'Si hay duda razonable, incluye una descripción corta y útil.'],
    citationImpact: ['La descripción normalmente no forma parte de la cita autor-fecha.'],
    referencePattern: 'Autor. (Fecha). Título [Descripción breve]. Fuente.',
  }),
  'no-title': verified({
    id: 'no-title', label: 'Obra sin título', manualSection: '9.22', manualPrintedPages: '298',
    whenToUse: 'Cuando la obra no proporciona un título.',
    rules: ['Sustituye el título por una descripción de la obra entre corchetes.', 'Cuando sea posible, incluye el medio dentro de una única descripción en vez de añadir dos descripciones.', 'Para un comentario sin título en una publicación periódica, usa hasta las primeras 20 palabras y luego una descripción.', 'Para una publicación social sin título, usa hasta las primeras 20 palabras del contenido en cursiva y después la descripción entre corchetes.'],
    citationImpact: ['Si además falta autor, la descripción ocupa la posición de autor y gobierna la cita.'],
    referencePattern: 'Autor. (Fecha). [Descripción de la obra y medio]. Fuente.',
    refuseWhen: ['No se comprobó si la obra tiene título visible o metadatos de título.', 'La descripción introduce información interpretativa no verificable.', 'Se usan dos descripciones redundantes cuando una sola identifica obra y medio.'],
  }),
  'source-definition': verified({
    id: 'source-definition', label: 'Definición de fuente', manualSection: '9.23', manualPrintedPages: '299',
    whenToUse: 'Para identificar dónde pueden recuperar los lectores la obra citada.',
    rules: ['Para una parte de un todo, la fuente es el contenedor mayor más DOI o URL cuando corresponda.', 'Para una obra independiente, la fuente puede ser editorial, base/archivo, red social o sitio web, más DOI o URL.', 'Para una obra asociada a un lugar específico, la fuente incluye ubicación y puede incluir DOI/URL.'],
    citationImpact: ['La fuente normalmente no aparece en la cita autor-fecha, pero determina que la obra sea recuperable.'],
    referencePattern: 'Autor. (Fecha). Título. Contenedor, editorial, archivo, plataforma o ubicación. DOI/URL',
  }),
  'source-element-format': verified({
    id: 'source-element-format', label: 'Formato del elemento fuente', manualSection: '9.24', manualPrintedPages: '299-300',
    whenToUse: 'Para construir una fuente de una o dos partes según la categoría.',
    rules: ['La fuente puede tener una parte, como editorial, o dos, como datos periódicos y DOI.', 'Los componentes dependen del tipo de referencia y deben seguir su plantilla.', 'Si autor y editorial o sitio son iguales, omite la editorial o sitio para evitar repetición.'],
    citationImpact: ['Omitir una fuente repetida no modifica la cita.'],
    referencePattern: 'Fuente principal. DOI/URL; si autor y fuente coinciden, no repitas el nombre.',
  }),
  'periodical-source': verified({
    id: 'periodical-source', label: 'Fuente de publicación periódica', manualSection: '9.25', manualPrintedPages: '300',
    whenToUse: 'Para revistas científicas, magazines, periódicos, boletines y blogs.',
    rules: ['Incluye título de la publicación, volumen, número, páginas o número de artículo según existan.', 'Escribe el título periódico en title case y cursiva, seguido de coma no cursiva.', 'Reproduce el título oficial de la publicación; no adoptes abreviaturas de bases externas.', 'Volumen va en cursiva; número inmediatamente entre paréntesis sin cursiva ni espacio.', 'Tras el número usa coma; páginas o número de artículo no van en cursiva.', 'Separa rangos de páginas con guion y páginas discontinuas con comas.', 'Termina la información periódica con punto y después DOI/URL.'],
    citationImpact: ['La cita sigue usando autor y año, no título de revista, volumen ni páginas del artículo salvo localizador textual.'],
    referencePattern: 'Título de la publicación, volumen(número), páginas o Artículo eLocator. DOI/URL',
  }),
  'periodical-missing-information': verified({
    id: 'periodical-missing-information', label: 'Publicación periódica en línea con información faltante', manualSection: '9.26', manualPrintedPages: '300',
    whenToUse: 'Cuando un artículo de periódico, blog u otra publicación en línea no tiene volumen, número ni páginas/eLocator.',
    rules: ['Omite volumen, número, páginas o artículo si no aparecen en la obra.', 'No reemplaces campos ausentes con texto inventado.', 'La fuente puede reducirse al título de la publicación periódica antes de la URL.'],
    citationImpact: ['Los datos periódicos ausentes no cambian la cita autor-fecha.'],
    referencePattern: 'Autor. (Fecha). Título del artículo. Título de la publicación. URL',
    refuseWhen: ['No se revisó si el dato realmente está ausente.', 'Se inventó volumen, número, páginas o eLocator.', 'Se confundió la falta de datos con una página web independiente.'],
  }),
  'article-number': verified({
    id: 'article-number', label: 'Número de artículo o eLocator', manualSection: '9.27', manualPrintedPages: '301',
    whenToUse: 'Cuando la publicación asigna número de artículo en lugar de rango de páginas.',
    rules: ['Escribe “Artículo” con mayúscula inicial y luego el identificador en lugar de páginas.', 'Si el PDF además muestra páginas, pueden usarse como localizador en citas, pero no se añaden a la referencia.'],
    citationImpact: ['Para una cita directa usa las páginas visibles del PDF si son estables; el eLocator identifica la obra en referencias.'],
    referencePattern: 'Revista, volumen(número), Artículo eLocator. DOI/URL',
  }),
  'edited-chapter-source': verified({
    id: 'edited-chapter-source', label: 'Fuente de capítulo editado o entrada de consulta', manualSection: '9.28', manualPrintedPages: '301-302',
    whenToUse: 'Cuando se cita un capítulo, definición o entrada dentro de una obra editada.',
    rules: ['La fuente es el libro editado u obra de consulta completa.', 'Escribe “En” y luego iniciales y apellidos no invertidos de editores.', 'Usa (Ed.) o (Eds.) después del editor final.', 'Añade coma, título del libro en estilo oración y cursiva, páginas entre paréntesis sin cursiva, punto y editorial.', 'Si existen edición y volumen, colócalos con las páginas en ese orden y separados por comas.', 'Un volumen con título propio integra Vol., número y título después del título principal.'],
    citationImpact: ['La cita corresponde al autor del capítulo o entrada, no al editor del contenedor.'],
    referencePattern: 'Autor del capítulo. (Fecha). Título. En E. Editor (Ed.), Título del libro (edición, Vol. x, pp. xx-xx). Editorial.',
  }),
  'publisher-source': verified({
    id: 'publisher-source', label: 'Casa editorial como fuente', manualSection: '9.29', manualPrintedPages: '302',
    whenToUse: 'Para libros, capítulos, informes, software, aplicaciones y conjuntos de datos que acreditan editorial.',
    rules: ['No incluyas ubicación geográfica de la editorial.', 'Escribe el nombre como aparece en la obra y no lo abrevies más de lo mostrado.', 'Conserva ortografía y mayúsculas de la edición utilizada aunque cambien entre años.', 'Usa el sello o división acreditado, no necesariamente la empresa matriz.', 'Omite designaciones societarias como Corp. o S.A.', 'Si aparecen varias editoriales, inclúyelas en orden separadas por punto y coma.', 'Si autor y editorial son iguales, omite la editorial.'],
    citationImpact: ['La editorial no forma parte de la cita autor-fecha.'],
    referencePattern: 'Autor. (Fecha). Título. Editorial 1; Editorial 2. DOI/URL',
  }),
  'database-archive-source': verified({
    id: 'database-archive-source', label: 'Base de datos o archivo como fuente', manualSection: '9.30', manualPrintedPages: '302-303',
    whenToUse: 'Cuando la base o archivo es necesaria para recuperar una obra exclusiva o de circulación limitada.',
    rules: ['Incluye base/archivo solo cuando sea necesaria para recuperar la obra exacta.', 'Inclúyela para contenido original exclusivo, tesis de circulación limitada, archivos universitarios, preprints, repositorios y fuentes primarias digitalizadas de archivo.', 'Omítela para obras ampliamente disponibles en bases académicas comunes.', 'El nombre de la base/archivo va como fuente, sin cursiva, seguido de DOI/URL.', 'Si una URL exige sesión o es específica de ella, usa la página pública de inicio o acceso.'],
    citationImpact: ['La base de datos no reemplaza al autor en la cita.'],
    referencePattern: 'Autor. (Fecha). Título [Descripción]. Nombre de la base o archivo. URL pública',
    refuseWhen: ['Se añade una base académica común a una obra ampliamente disponible.', 'La URL contiene una sesión, token o acceso privado.', 'No se verificó que la base publique contenido exclusivo o de circulación limitada.'],
  }),
  'specific-location-source': verified({
    id: 'specific-location-source', label: 'Obra con ubicación específica', manualSection: '9.31', manualPrintedPages: '303-304',
    whenToUse: 'Para presentaciones, congresos u obras asociadas a un lugar físico concreto.',
    rules: ['Incluye ciudad, estado/provincia/territorio cuando corresponda y país.', 'Usa abreviaturas postales adecuadas para subdivisiones cuando existan.', 'La ubicación ayuda a identificar o recuperar la obra y no sustituye DOI/URL cuando estos corresponden.'],
    citationImpact: ['La ubicación no aparece en la cita autor-fecha.'],
    referencePattern: 'Nombre del evento, Ciudad, subdivisión, País. DOI/URL',
  }),
  'social-media-source': verified({
    id: 'social-media-source', label: 'Red social como fuente', manualSection: '9.32', manualPrintedPages: '304',
    whenToUse: 'Cuando el contenido fue publicado originalmente en una red social.',
    rules: ['Usa la red como fuente solo para contenido originado allí.', 'Si la red solo enlazó a otra obra, cita directamente esa obra.', 'Escribe el nombre de la red en title case sin cursiva, seguido de punto y URL.', 'Menciona la vía de descubrimiento solo si es metodológicamente relevante.'],
    citationImpact: ['La cita usa el titular de la cuenta y año, no el nombre de la red.'],
    referencePattern: 'Titular [@usuario]. (Fecha). Contenido [Tipo]. Red social. URL',
  }),
  'website-source': verified({
    id: 'website-source', label: 'Sitio web como fuente', manualSection: '9.33', manualPrintedPages: '304',
    whenToUse: 'Cuando el tipo correcto es una página web y el sitio contiene la obra.',
    rules: ['Escribe el nombre del sitio en title case sin cursiva.', 'Añade punto y URL.', 'Si autor y sitio son iguales, omite el nombre del sitio y deja solo la URL como fuente.'],
    citationImpact: ['La cita usa autor y año; el sitio no entra salvo que sea el autor.'],
    referencePattern: 'Autor. (Fecha). Título. Sitio si difiere. URL',
  }),
  'when-to-include-doi-url': verified({
    id: 'when-to-include-doi-url', label: 'Cuándo incluir DOI o URL', manualSection: '9.34', manualPrintedPages: '304-305',
    whenToUse: 'Para decidir el componente final de la referencia.',
    rules: ['Incluye DOI para toda obra que lo tenga, sea consultada en línea o impresa.', 'Una obra impresa sin DOI no lleva DOI ni URL.', 'Si una obra en línea tiene DOI y URL, incluye solo DOI.', 'Una obra en línea sin DOI de un sitio web lleva URL funcional directa.', 'Una obra ampliamente disponible en una base académica común no lleva URL ni base.', 'Para base exclusiva o circulación limitada incluye base/archivo y URL; si exige sesión, usa la página pública de acceso.', 'Una URL debe enlazar directamente a la obra o contenido específico cuando sea posible.', 'ISBN e ISSN no se incluyen.', 'Si el enlace ya no funciona, aplica la regla de obra sin fuente.'],
    citationImpact: ['DOI y URL no aparecen en la cita autor-fecha.'],
    referencePattern: '… Fuente. https://doi.org/xxxxx o URL funcional',
  }),
  'doi-url-format': verified({
    id: 'doi-url-format', label: 'Formato de DOI y URL', manualSection: '9.35', manualPrintedPages: '305-306',
    whenToUse: 'Para escribir y comprobar enlaces al final de una referencia.',
    rules: ['Presenta DOI y URL como enlaces completos http:// o https://.', 'No antepongas “Recuperado de” ni “Accedido desde”, salvo el patrón especial con fecha de recuperación.', 'Los enlaces pueden mostrarse con estilo de hipervínculo o como texto, según el documento.', 'Deben ser funcionales si el trabajo se leerá en línea.', 'Normaliza DOI antiguos a https://doi.org/xxxxx.', 'Copia el enlace directamente para evitar errores y conserva mayúsculas/puntuación.', 'No insertes saltos manuales ni punto final después del enlace.'],
    citationImpact: ['El formato visual del enlace no afecta la cita.'],
    referencePattern: 'https://doi.org/10.xxxx/xxxxx o https://sitio/ruta',
    refuseWhen: ['El DOI o URL no resuelve a la obra citada.', 'Se modificó la capitalización o puntuación interna del enlace.', 'Se añadió un punto final que rompe la funcionalidad.'],
  }),
  'shortened-doi-url': verified({
    id: 'shortened-doi-url', label: 'DOI o URL acortados', manualSection: '9.36', manualPrintedPages: '306',
    whenToUse: 'Cuando el DOI o URL original es largo o complejo.',
    rules: ['Puede usarse shortDOI o URL acortada.', 'Para DOI usa el servicio oficial shortDOI; la obra sigue teniendo un solo DOI.', 'Cualquier URL acortada es aceptable únicamente si se verifica que conduce a la ubicación correcta.'],
    citationImpact: ['El enlace acortado no modifica la cita autor-fecha.'],
    referencePattern: '… Fuente. URL acortada verificada',
    refuseWhen: ['El enlace acortado no se abrió y verificó.', 'El acortador oculta un destino distinto o inseguro.', 'Se trata el shortDOI como un DOI adicional de la obra.'],
  }),
  'no-source': verified({
    id: 'no-source', label: 'Obra sin fuente recuperable', manualSection: '9.37', manualPrintedPages: '306',
    whenToUse: 'Cuando los lectores no pueden recuperar la obra citada.',
    rules: ['Una referencia sin fuente recuperable no puede incluirse en la lista.', 'Correos personales, clases no grabadas y fuentes privadas de intranet normalmente se citan solo como comunicaciones personales.'],
    citationImpact: ['Usa el formato de comunicación personal en el texto cuando corresponda.'],
    referencePattern: 'Sin entrada en referencias; cita en texto: (A. Apellido, comunicación personal, fecha exacta).',
    refuseWhen: ['Se intenta fabricar una URL o fuente inexistente.', 'La obra no puede ser recuperada por el público destinatario.', 'Se propone una entrada sin ningún elemento fuente.'],
  }),
  'other-language-work': verified({
    id: 'other-language-work', label: 'Obra en otro idioma', manualSection: '9.38', manualPrintedPages: '307',
    whenToUse: 'Cuando la obra consultada está en un idioma distinto del idioma del trabajo.',
    rules: ['Conserva autor, fecha, título y fuente en el idioma original.', 'Añade inmediatamente después del título una traducción entre corchetes, antes del punto.', 'Si citas una parte de un todo, traduce solo el título de la parte, no el título del contenedor.', 'La traducción puede ser descriptiva y gramaticalmente natural; debe permitir comprender de qué trata la obra.', 'Cuando el título usa una escritura no romana, translitéralo al alfabeto romano si es posible y añade siempre la traducción entre corchetes.', 'Si no puede transliterarse, puede conservarse la escritura original y debe decidirse el orden alfabético mediante una guía lingüística o un precedente consistente.'],
    citationImpact: ['La cita usa el autor y año; la traducción del título solo gobierna la cita cuando falta autor.'],
    referencePattern: 'Autor. (Fecha). Título original o transliterado [Traducción del título]. Fuente.',
  }),
  'translated-work': verified({
    id: 'translated-work', label: 'Obra traducida', manualSection: '9.39', manualPrintedPages: '307-308',
    whenToUse: 'Cuando se leyó y citó una traducción publicada de una obra.',
    rules: ['Referencia la versión traducida efectivamente consultada.', 'Acredita a la persona traductora en la posición indicada por la plantilla del tipo de obra.', 'Al final añade entre paréntesis el año de publicación original.', 'No presentes como consultada la edición original si solo leíste la traducción.'],
    citationImpact: ['La cita muestra el año original y el de la traducción, separados por barra, según 8.15.'],
    referencePattern: 'Autor. (Año de traducción). Título (A. Traductor, Trad.). Editorial. (Obra original publicada en año)',
  }),
  'reprinted-work': verified({
    id: 'reprinted-work', label: 'Obra reimpresa', manualSection: '9.40', manualPrintedPages: '308',
    whenToUse: 'Cuando la misma obra fue publicada en dos lugares y ambas versiones continúan disponibles.',
    rules: ['Da primero los datos completos de la versión que se leyó.', 'Añade después, entre paréntesis, la información de publicación original exigida por la plantilla.', 'La nota de publicación original evita que las dos apariciones parezcan obras distintas.'],
    citationImpact: ['La cita incluye los años de la publicación original y la reimpresión según 8.15.'],
    referencePattern: 'Referencia completa de la versión consultada. (Trabajo original publicado en Fuente original, año original)',
  }),
  'republished-reissued-work': verified({
    id: 'republished-reissued-work', label: 'Obra republicada o reeditada', manualSection: '9.41', manualPrintedPages: '308',
    whenToUse: 'Cuando una obra agotada se publicó de nuevo, se reeditó o se incorporó a una antología posterior.',
    rules: ['Referencia la nueva publicación utilizada.', 'Añade al final “Obra original publicada en” y el año original entre paréntesis.', 'Trata una obra anterior incorporada a una antología como republicada, no como reimpresa.', 'En música, una reedición se trata de forma equivalente.'],
    citationImpact: ['La cita incluye el año original y el de la nueva publicación según 8.15.'],
    referencePattern: 'Autor. (Año de nueva publicación). Título. Fuente. (Obra original publicada en año)',
  }),
  'religious-classical-work': verified({
    id: 'religious-classical-work', label: 'Obra religiosa o clásica', manualSection: '9.42', manualPrintedPages: '308-309',
    whenToUse: 'Para escrituras religiosas y obras antiguas o clásicas republicadas o traducidas.',
    rules: ['Trata estas obras como libros.', 'Una obra religiosa suele carecer de autor; una versión anotada puede acreditar al editor en posición de autor.', 'Incluye la fecha de la versión consultada y omite el año original si es desconocido o discutido.', 'Acredita al traductor cuando se consultó una traducción.', 'Trata la literatura griega, romana y clásica antigua como republicada.', 'Usa A.E.C. para fechas antiguas y ca. para fechas aproximadas; no añadas E.C. o A.D. a fechas comunes.', 'Para pasajes concretos usa divisiones canónicas numeradas en vez de páginas.'],
    citationImpact: ['La cita de una obra republicada usa año original y año de la versión; para una cita directa añade la división canónica.'],
    referencePattern: 'Título o Autor. (Año de versión). Título (Trad./Ed.). Editorial. (Obra original publicada ca. año A.E.C.)',
  }),
  'reference-list-format': verified({
    id: 'reference-list-format', label: 'Formato de la lista de referencias', manualSection: '9.43', manualPrintedPages: '309',
    whenToUse: 'Al preparar la sección final de referencias del trabajo.',
    rules: ['Comienza la lista en una página nueva después del texto.', 'Usa el encabezado “Referencias” centrado y en negrita.', 'Ordena las entradas alfabéticamente por autor.', 'Aplica doble espacio a toda la lista, dentro y entre entradas.', 'Usa sangría francesa de 0.5 pulgadas o 1.27 cm en cada entrada.'],
    citationImpact: ['Toda obra citada recuperable debe poder vincularse con una entrada de la lista, salvo las excepciones expresas.'],
    referencePattern: 'Referencias; entradas alfabéticas con doble espacio y sangría francesa de 1.27 cm.',
  }),
  'reference-list-alphabetical-order': verified({
    id: 'reference-list-alphabetical-order', label: 'Orden alfabético general', manualSection: '9.44', manualPrintedPages: '309-310',
    whenToUse: 'Para ordenar todas las entradas de la lista.',
    rules: ['Ordena por el primer elemento de cada entrada, normalmente el apellido del primer autor seguido de sus iniciales.', 'Alfabetiza letra por letra: cuando una forma está contenida en otra, “nada precede a algo”.', 'Ignora espacios y signos de puntuación en apellidos de dos palabras, y también el contenido entre paréntesis o corchetes.', 'Ordena los sufijos de nacimiento como II y III cronológicamente, con el mayor primero.', 'Ordena prefijos y partículas según la forma del apellido presentada por el autor.'],
    citationImpact: ['El orden de la lista no cambia la cita, pero debe permitir localizarla por su primer elemento.'],
    referencePattern: 'Entradas ordenadas letra por letra según el primer elemento.',
  }),
  'surname-name-order': verified({
    id: 'surname-name-order', label: 'Orden de apellidos y nombres', manualSection: '9.45', manualPrintedPages: '310',
    whenToUse: 'Cuando la estructura cultural del nombre o apellido no resulta evidente.',
    rules: ['Determina la forma preferida por la persona autora mediante su sitio, institución, biografía, CV o publicaciones previas.', 'Una vez identificado el apellido, escribe la referencia en forma Apellido, Iniciales.', 'Conserva nombres compuestos, partículas y capitalización según la preferencia verificada.'],
    citationImpact: ['La cita usa el apellido verificado y debe coincidir con la referencia.'],
    referencePattern: 'Apellido verificado, Iniciales. (Fecha). Título. Fuente.',
    refuseWhen: ['Se adivinó qué parte del nombre es el apellido.', 'Se invirtió un nombre institucional o culturalmente inseparable.', 'La forma usada contradice la presentación consistente del propio autor.'],
  }),
  'same-first-author-order': verified({
    id: 'same-first-author-order', label: 'Varias obras del mismo primer autor', manualSection: '9.46', manualPrintedPages: '310-311',
    whenToUse: 'Cuando dos o más entradas comienzan con el mismo autor.',
    rules: ['Repite el nombre del autor en cada entrada; no lo sustituyas por una raya.', 'Las entradas de un solo autor se ordenan cronológicamente: s. f. primero, luego años del más antiguo al reciente y “en prensa” al final.', 'Una entrada de un solo autor precede a entradas de varios autores que comienzan con el mismo nombre, aunque sea posterior.', 'Con la misma lista completa de autores y el mismo orden, ordena cronológicamente.', 'Cuando cambian los coautores, ordena alfabéticamente por el apellido del segundo autor y continúa con el tercero si hace falta.'],
    citationImpact: ['Las citas conservan el año correspondiente; si autor y año también coinciden, aplica 9.47.'],
    referencePattern: 'Mismo autor: s. f. → años ascendentes → en prensa; luego coautorías por apellidos sucesivos.',
  }),
  'same-author-same-date-order': verified({
    id: 'same-author-same-date-order', label: 'Mismo autor y misma fecha', manualSection: '9.47', manualPrintedPages: '311-312',
    whenToUse: 'Cuando varias obras tienen autores idénticos en el mismo orden y la misma fecha.',
    rules: ['Añade letras minúsculas inmediatamente después del año: 2020a, 2020b; también s. f.-a y en prensa-a.', 'Primero ordena por fecha: una referencia con solo año precede a una fecha más específica, y fechas específicas se ordenan cronológicamente.', 'Si las fechas son idénticas, alfabetiza por título ignorando artículos iniciales como Un, Una, El y La.', 'Si las obras son partes numeradas de una misma serie, ordénalas por el orden de la serie y no por título.', 'Las letras asignadas en referencias deben mantenerse en las citas.'],
    citationImpact: ['Incluye la letra junto al año en todas las citas para distinguir las obras.'],
    referencePattern: 'Autor. (2020a). Título A… / Autor. (2020b). Título B…',
  }),
  'same-surname-first-authors': verified({
    id: 'same-surname-first-authors', label: 'Primeros autores con el mismo apellido', manualSection: '9.48', manualPrintedPages: '312',
    whenToUse: 'Cuando distintas personas que son primer autor comparten apellido.',
    rules: ['Ordena las entradas alfabéticamente por las iniciales del primer autor.', 'La regla se aplica únicamente al primer autor de cada referencia.', 'Si además comparten apellido e iniciales, ordénalas con las reglas 9.46 y 9.47 aunque sean personas diferentes o una haya cambiado de nombre.'],
    citationImpact: ['Incluye las iniciales del primer autor en las citas según 8.20 para evitar ambigüedad.'],
    referencePattern: 'Taylor, J. M., … antes de Taylor, T., …',
  }),
  'no-author-anonymous-order': verified({
    id: 'no-author-anonymous-order', label: 'Orden de obras sin autor o anónimas', manualSection: '9.49', manualPrintedPages: '312',
    whenToUse: 'Cuando una entrada comienza por título o está firmada como Anónimo.',
    rules: ['Comprueba primero si existe un autor grupal.', 'Solo una obra firmada “Anónimo” comienza por Anónimo y se alfabetiza como un nombre real.', 'Una obra verdaderamente sin autor comienza por el título.', 'Alfabetiza por la primera palabra significativa del título e ignora Un, Una, El y La iniciales.', 'Alfabetiza los números como si estuvieran escritos con palabras completas.'],
    citationImpact: ['La cita de una obra sin autor usa el título; la de una obra firmada usa Anónimo.'],
    referencePattern: 'Título significativo. (Fecha). Fuente. o Anónimo. (Fecha). Título. Fuente.',
  }),
  'reference-abbreviations': verified({
    id: 'reference-abbreviations', label: 'Abreviaturas en referencias', manualSection: '9.50', manualPrintedPages: '312-313',
    whenToUse: 'Para abreviar componentes bibliográficos previstos por APA.',
    rules: ['Usa las abreviaturas previstas para ahorrar espacio; muchas, aunque no todas, llevan mayúscula.', 'ed. significa edición; ed. rev., edición revisada; 2.ª ed., segunda edición.', 'Ed. y Eds. significan editor y editores.', 'Trad. significa traductor o traductores; Narr. y Narrs., narrador y narradores.', 's. f. significa sin fecha; p. y pp., página y páginas; párr. y párrs., párrafo y párrafos; Vol. y Vols., volumen y volúmenes.', 'No inventes una abreviatura para un componente no contemplado por la plantilla.'],
    citationImpact: ['Las abreviaturas de edición o función no entran normalmente en la cita; p., pp. y párr. se usan como localizadores cuando corresponda.'],
    referencePattern: '(2.ª ed., Vol. 2, pp. 10-20); (A. Traductor, Trad.)',
  }),
  'annotated-bibliography': verified({
    id: 'annotated-bibliography', label: 'Bibliografía anotada', manualSection: '9.51', manualPrintedPages: '313',
    whenToUse: 'Cuando el encargo requiere referencias acompañadas de anotaciones descriptivas o evaluativas.',
    rules: ['Aplica las reglas APA de referencias y el formato general del trabajo; los requisitos particulares los define el docente.', 'Ordena las entradas alfabéticamente como una lista de referencias.', 'Coloca cada anotación como párrafo nuevo debajo de su entrada.', 'Aplica 0.5 pulgadas o 1.27 cm de sangría a toda la anotación, sin sangría adicional en su primera línea.', 'Si la anotación tiene varios párrafos, añade 0.5 pulgadas de sangría a la primera línea del segundo y siguientes.', 'No es necesario citar la propia obra anotada cuando el contexto deja claro que procede de ella; sí cita otras obras mencionadas dentro de la anotación.'],
    citationImpact: ['La propia entrada identifica la fuente comentada; otras fuentes usadas en la anotación requieren citas y referencias.'],
    referencePattern: 'Entrada APA con sangría francesa; debajo, anotación con sangría izquierda de 1.27 cm.',
  }),
  'meta-analysis-references': verified({
    id: 'meta-analysis-references', label: 'Referencias incluidas en un metaanálisis', manualSection: '9.52', manualPrintedPages: '313',
    whenToUse: 'Cuando una lista incluye los estudios analizados y otras referencias metodológicas o contextuales.',
    rules: ['Integra todos los estudios del metaanálisis en la lista alfabética general; no crees una lista aparte.', 'Coloca un asterisco al inicio de cada entrada correspondiente a un estudio incluido.', 'Debajo del encabezado Referencias, inserta como nuevo párrafo con sangría la declaración: “Las referencias marcadas con asterisco indican estudios incluidos en el metaanálisis.”', 'Los estudios incluidos no tienen que citarse en el texto, aunque pueden citarse si el autor lo considera útil.', 'Las citas dentro del texto no llevan asterisco.'],
    citationImpact: ['La excepción permite incluir estudios analizados sin cita textual; cualquier cita que sí se haga usa el formato autor-fecha normal y sin asterisco.'],
    referencePattern: '*Autor. (Fecha). Título. Fuente.',
  }),
};

export function getReferenceRule(id: ReferenceRuleId): Apa7VerifiedReferenceRule {
  return referenceRules[id];
}
