import { z } from 'zod';

export const principlesEthicsRuleId = z.enum([
  'quantitative-articles', 'qualitative-articles', 'mixed-methods-articles',
  'replication-articles', 'meta-analysis-articles', 'literature-review-articles',
  'theoretical-articles', 'methodological-articles', 'other-article-types',
  'student-papers-theses', 'ethical-compliance-planning',
  'ethical-reporting-results', 'errors-corrections-retractions',
  'data-retention-sharing', 'qualitative-data-confidentiality',
  'duplicate-piecemeal-publication', 'plagiarism-self-plagiarism',
  'participant-rights-welfare', 'confidentiality-protection',
  'conflicts-of-interest', 'publication-credit', 'author-order',
  'reviewer-conflict-during-review', 'unpublished-manuscript-rights',
  'ethical-compliance-checklist',
]);

export type PrinciplesEthicsRuleId = z.infer<typeof principlesEthicsRuleId>;

export interface Apa7VerifiedPrinciplesEthicsRule {
  id: PrinciplesEthicsRuleId;
  label: string;
  manualSection: `1.${number}`;
  manualPrintedPages: string;
  status: 'verified';
  rules: string[];
  citationTreatment: string[];
  referenceTreatment: string[];
  refuseWhen: string[];
}

const verified = (rule: Omit<Apa7VerifiedPrinciplesEthicsRule, 'status' | 'citationTreatment' | 'referenceTreatment' | 'refuseWhen'> & Partial<Pick<Apa7VerifiedPrinciplesEthicsRule, 'citationTreatment' | 'referenceTreatment' | 'refuseWhen'>>): Apa7VerifiedPrinciplesEthicsRule => ({
  ...rule,
  status: 'verified',
  citationTreatment: rule.citationTreatment ?? ['Cita toda idea, método, dato, instrumento o texto ajeno que sustente el escrito; la categoría del artículo no elimina la atribución.'],
  referenceTreatment: rule.referenceTreatment ?? ['Incluye una entrada recuperable para cada obra citada y no añadas obras no consultadas o no citadas.'],
  refuseWhen: rule.refuseWhen ?? ['Falta evidencia para afirmar autoría, aprobación, consentimiento, originalidad, corrección o cumplimiento ético.', 'Se pide ocultar procedencia, duplicación, conflicto, error, retractación o reutilización de datos.', 'Se pretende inventar citas, referencias, datos, permisos, contribuciones o decisiones editoriales.'],
});

export const principlesEthicsRules: Record<PrinciplesEthicsRuleId, Apa7VerifiedPrinciplesEthicsRule> = {
  'quantitative-articles': verified({ id: 'quantitative-articles', label: 'Artículos cuantitativos', manualSection: '1.1', manualPrintedPages: '4-5', rules: ['Reportan investigaciones que miden variables y analizan datos numéricos para describir, estimar, probar o modelar relaciones.', 'Identifica pregunta, hipótesis, diseño, muestra, medidas, análisis, resultados y limitaciones.', 'Usa los módulos JARS-Quant aplicables al diseño real.', 'No presentes asociación como causalidad ni significación como magnitud.'] }),
  'qualitative-articles': verified({ id: 'qualitative-articles', label: 'Artículos cualitativos', manualSection: '1.2', manualPrintedPages: '5-6', rules: ['Reportan investigación basada en datos no numéricos y procesos interpretativos situados.', 'Explicita enfoque, contexto, participantes o fuentes, reflexividad, recolección, análisis, integridad y hallazgos.', 'Usa JARS-Qual sin forzar una estructura cuantitativa incompatible.', 'Distingue claramente voces de participantes, interpretación del equipo y literatura externa.'], citationTreatment: ['Los extractos de participantes del propio estudio no son referencias; las obras documentales, métodos y teorías externas sí se citan.'], referenceTreatment: ['Referencia fuentes externas recuperables y no listes participantes o entrevistas confidenciales del estudio.'] }),
  'mixed-methods-articles': verified({ id: 'mixed-methods-articles', label: 'Artículos de métodos mixtos', manualSection: '1.3', manualPrintedPages: '6', rules: ['Integran de forma metodológica componentes cualitativos y cuantitativos para responder una pregunta.', 'Justifica la combinación y describe diseño, secuencia, prioridad y puntos de integración.', 'Aplica los JARS de ambos componentes y JARS-Mixed.', 'No llames método mixto a yuxtaponer texto y números sin integración.'] }),
  'replication-articles': verified({ id: 'replication-articles', label: 'Artículos de réplica', manualSection: '1.4', manualPrintedPages: '6-7', rules: ['Repiten total o parcialmente un estudio para evaluar la reproducibilidad o generalidad de sus hallazgos.', 'Identifica el estudio objetivo, tipo de réplica, similitudes, cambios y criterios de comparación.', 'Explica desviaciones y evita presentar como fracaso una diferencia sin considerar precisión y contexto.', 'Una réplica merece evaluación por rigor y contribución, no por coincidir con el original.'], citationTreatment: ['Cita de forma inequívoca el estudio replicado y las obras que justifican modificaciones.'], referenceTreatment: ['Incluye la referencia completa del estudio original y de protocolos o materiales citados.'] }),
  'meta-analysis-articles': verified({ id: 'meta-analysis-articles', label: 'Meta-análisis cuantitativos y cualitativos', manualSection: '1.5', manualPrintedPages: '7-8', rules: ['Sintetizan sistemáticamente resultados o hallazgos de estudios previos mediante procedimientos cuantitativos o cualitativos explícitos.', 'Reporta pregunta, protocolo, búsqueda, selección, corpus, evaluación, síntesis, incertidumbre y límites.', 'Distingue revisión sistemática, metaanálisis cuantitativo y metasíntesis cualitativa.', 'No denomines meta-análisis a una revisión narrativa sin método de síntesis.'], citationTreatment: ['Identifica cuáles estudios fueron incluidos y distingue esas citas de las usadas solo como contexto.'], referenceTreatment: ['Referencia los estudios citados; si se usa un asterisco para señalar incluidos, explícalo al inicio de la lista.'] }),
  'literature-review-articles': verified({ id: 'literature-review-articles', label: 'Artículos de revisión de la literatura', manualSection: '1.6', manualPrintedPages: '8', rules: ['Evalúan, organizan y sintetizan investigación publicada sobre un problema.', 'Define alcance, criterios y lógica de organización suficientes para entender la selección.', 'Resume el estado del conocimiento, acuerdos, contradicciones, vacíos y direcciones futuras.', 'No presentes una búsqueda selectiva como exhaustiva.'], citationTreatment: ['Cita fuentes primarias para los hallazgos y usa citas secundarias solo cuando no se consultó el original.'], referenceTreatment: ['Incluye únicamente las obras citadas y verificadas; una bibliografía exhaustiva es distinta de una lista APA ordinaria.'] }),
  'theoretical-articles': verified({ id: 'theoretical-articles', label: 'Artículos teóricos', manualSection: '1.7', manualPrintedPages: '8', rules: ['Desarrollan, refinan, comparan o analizan teoría a partir de la literatura existente.', 'Explicita supuestos, conceptos, relaciones, alcance y predicciones o implicaciones.', 'Contrasta teorías con evidencia pertinente y reconoce explicaciones alternativas.', 'No atribuyas a una teoría afirmaciones que su fuente no sostiene.'] }),
  'methodological-articles': verified({ id: 'methodological-articles', label: 'Artículos metodológicos', manualSection: '1.8', manualPrintedPages: '8-9', rules: ['Presentan métodos, herramientas, diseños o análisis nuevos o modificados.', 'Describe el método con detalle reproducible y demuestra su utilidad, supuestos y límites.', 'Compara con alternativas de manera justa y proporciona ejemplos o datos cuando correspondan.', 'Distingue una contribución metodológica de una simple aplicación.'], citationTreatment: ['Cita métodos precedentes, algoritmos, software, datos e instrumentos usados para desarrollar o comparar la propuesta.'], referenceTreatment: ['Referencia documentación y versiones verificables de métodos y software citados.'] }),
  'other-article-types': verified({ id: 'other-article-types', label: 'Otros tipos de artículos', manualSection: '1.9', manualPrintedPages: '9', rules: ['Comentarios, informes breves, cartas, obituarios, reseñas, estudios de caso u otros géneros siguen políticas específicas de la revista.', 'Identifica el género real antes de aplicar estructura y extensión.', 'Mantén los estándares éticos, de atribución y precisión aunque el formato sea breve.', 'No adaptes por analogía una plantilla de referencia sin determinar el tipo de obra.'] }),
  'student-papers-theses': verified({ id: 'student-papers-theses', label: 'Escritos, disertaciones y tesis de estudiantes', manualSection: '1.10', manualPrintedPages: '9-11', rules: ['La consigna, rúbrica y plantilla institucional prevalecen en requisitos específicos.', 'Distingue trabajo de curso, proyecto final, tesis y disertación; no todos requieren los elementos de un manuscrito profesional.', 'Mantén integridad, atribución, confidencialidad y precisión académicas.', 'Consulta a docente o asesor cuando el manual ofrece variantes.', 'No añadas requisitos profesionales —como título abreviado o nota del autor— si no se solicitan.'], citationTreatment: ['Aplica autor-fecha y localizadores como en otros escritos, además de cualquier regla explícita del curso.'], referenceTreatment: ['Usa la lista APA salvo que la institución exija otra norma; registra la excepción en vez de mezclar estilos silenciosamente.'] }),
  'ethical-compliance-planning': verified({ id: 'ethical-compliance-planning', label: 'Planificación para el cumplimiento ético', manualSection: '1.11', manualPrintedPages: '11-12', rules: ['Planifica ética antes de recoger, analizar o publicar datos.', 'Obtén revisión y aprobación institucional cuando sea necesaria y cumple códigos profesionales, leyes y políticas.', 'Define consentimiento, privacidad, seguridad, manejo de datos, conflictos, autoría y difusión.', 'No uses el estilo APA como sustituto de aprobación ética o asesoría jurídica.'], citationTreatment: ['Cita códigos, normativas o protocolos cuando se discutan como autoridades; un número de aprobación se reporta como identificador, no como cita inventada.'], referenceTreatment: ['Referencia códigos o políticas recuperables citados; conserva documentación de aprobación fuera de la bibliografía.'] }),
  'ethical-reporting-results': verified({ id: 'ethical-reporting-results', label: 'Comunicación ética y precisa de resultados', manualSection: '1.12', manualPrintedPages: '12-13', rules: ['No fabriques, falsifiques, omitas selectivamente ni presentes de forma engañosa datos o resultados.', 'Reporta decisiones analíticas, exclusiones, resultados negativos y limitaciones necesarios para una interpretación honesta.', 'No manipules imágenes, tablas o estadísticas de forma que cambie el significado.', 'Distingue datos, inferencias y opiniones.', 'Corrige el registro cuando descubras un error material.'], citationTreatment: ['No uses una cita como respaldo si la fuente no apoya la afirmación o si omites evidencia contraria relevante.'], referenceTreatment: ['Verifica cada referencia contra la obra original y no cites una publicación retractada como evidencia vigente sin advertirlo.'], refuseWhen: ['Se pide fabricar o alterar datos, resultados, imágenes o significación.', 'Se pretende ocultar un resultado relevante, exclusión o limitación.', 'No puede verificarse que la fuente respalde la afirmación.'] }),
  'errors-corrections-retractions': verified({ id: 'errors-corrections-retractions', label: 'Errores, correcciones y retractaciones', manualSection: '1.13', manualPrintedPages: '13', rules: ['Un error menor puede corregirse en pruebas; un error publicado material requiere aviso de corrección y un problema que invalida el trabajo puede requerir retractación.', 'Notifica prontamente a editor y coautores y describe alcance del error.', 'No alteres silenciosamente el registro publicado.', 'Distingue corrección, retractación y expresión de preocupación.'], citationTreatment: ['Consulta el estado actual de la obra; si una corrección o retractación afecta la afirmación, cítala o adviértela.', 'No cites como evidencia válida un resultado retractado sin contexto explícito.'], referenceTreatment: ['Una corrección o retractación recuperable puede tener su propia referencia vinculada al artículo original.'] }),
  'data-retention-sharing': verified({ id: 'data-retention-sharing', label: 'Retención y uso compartido de datos', manualSection: '1.14', manualPrintedPages: '13-16', rules: ['Conserva datos y documentación durante el periodo exigido por institución, financiador, revista, ley o acuerdo.', 'Después de publicar, comparte datos razonablemente necesarios para verificar resultados con investigadores cualificados cuando ética, consentimiento, propiedad y confidencialidad lo permitan.', 'Establece condiciones para uso, seguridad, atribución, costos y destrucción o devolución.', 'No retengas datos solo para impedir comprobación ni prometas apertura incompatible con el consentimiento.', 'Usa repositorios y planes de gestión apropiados.'], citationTreatment: ['Cita el conjunto de datos reutilizado y el artículo asociado cuando ambos aporten información.', 'Los datos propios depositados pueden citarse como conjunto de datos para permitir recuperación.'], referenceTreatment: ['Incluye referencia del conjunto de datos con autor, fecha, título, versión, repositorio y DOI/URL disponibles.'], refuseWhen: ['Compartir vulneraría consentimiento, confidencialidad, ley, contrato o derechos de terceros.', 'No se verificó la versión o procedencia del conjunto.', 'Se pretende omitir atribución o condiciones de reutilización.'] }),
  'qualitative-data-confidentiality': verified({ id: 'qualitative-data-confidentiality', label: 'Confidencialidad adicional de datos cualitativos', manualSection: '1.15', manualPrintedPages: '16-17', rules: ['Los datos cualitativos pueden permitir reidentificación por contexto, voz o combinación de detalles aun sin nombres.', 'Evalúa consentimiento, relaciones, daño, propiedad comunitaria y posibilidad real de anonimización antes de compartir.', 'Puede ser ético restringir acceso, redactar detalles, usar extractos seleccionados o no compartir datos brutos.', 'Explica límites de disponibilidad sin revelar información protegida.', 'No prometas anonimato absoluto si el diseño no puede garantizarlo.'], citationTreatment: ['Los extractos de participantes del estudio se identifican conforme al protocolo y no se convierten en referencias personales.', 'Archivos cualitativos públicos externos sí se citan según su tipo.'], referenceTreatment: ['No incluyas participantes o archivos confidenciales en la lista; referencia repositorios o corpus externos recuperables.'] }),
  'duplicate-piecemeal-publication': verified({ id: 'duplicate-piecemeal-publication', label: 'Publicación duplicada y parcial', manualSection: '1.16', manualPrintedPages: '17-21', rules: ['No publiques el mismo manuscrito o resultados sustancialmente equivalentes como si fueran originales.', 'Evita fragmentar un estudio en múltiples informes mínimos cuando distorsione la evidencia o oculte su relación.', 'Una nueva publicación de los mismos datos puede ser legítima si responde una pregunta distinta, añade contribución sustancial y revela claramente el solapamiento.', 'Informa al editor sobre manuscritos relacionados, preprints, tesis y reutilización de datos.', 'Cita reportes previos del mismo conjunto y explica diferencias.'], citationTreatment: ['Cita los informes anteriores que usan los mismos datos y declara en la nota del autor o método la relación pertinente.'], referenceTreatment: ['Incluye referencias de publicaciones previas relacionadas; no las omitas para aparentar novedad.'], refuseWhen: ['Se pretende ocultar que datos o texto ya fueron publicados.', 'No puede determinarse el grado de solapamiento con reportes previos.', 'Se busca dividir resultados para inflar producción sin justificación científica.'] }),
  'plagiarism-self-plagiarism': verified({ id: 'plagiarism-self-plagiarism', label: 'Plagio y autoplagio', manualSection: '1.17', manualPrintedPages: '21', rules: ['Plagio es presentar palabras, ideas, imágenes o datos de otra fuente como propios; puede ocurrir aunque exista referencia si la copia textual no se marca.', 'Autoplagio es presentar trabajo propio previamente difundido como nuevo sin revelar su origen o reutilizar texto en grado engañoso.', 'Parafrasea de forma genuina y cita; usa comillas o bloque y localizador para texto exacto.', 'La reutilización limitada de lenguaje metodológico puede depender del contexto editorial, pero debe evitar engaño y respetar derechos.', 'No uses detectores de similitud como prueba definitiva de plagio o ausencia de él.'], citationTreatment: ['Idea parafraseada: autor y año; texto exacto: autor, año y localizador, con comillas o bloque.', 'Una obra propia anterior se cita como cualquier otra cuando sustenta o precede el nuevo trabajo.'], referenceTreatment: ['Incluye la fuente consultada y citada; en una cita secundaria referencia solo la obra realmente consultada.'], refuseWhen: ['Se pide ocultar copia, parafrasear para evadir detección o fabricar una fuente.', 'No se conoce la fuente original del material.', 'Se pretende certificar ausencia de plagio solo mediante porcentaje de similitud.'] }),
  'participant-rights-welfare': verified({ id: 'participant-rights-welfare', label: 'Derechos y bienestar de participantes y sujetos', manualSection: '1.18', manualPrintedPages: '21-22', rules: ['Protege dignidad, seguridad, consentimiento, voluntariedad y derecho a retirarse conforme a la revisión ética aplicable.', 'Minimiza riesgos y evita coerción, engaño injustificado o explotación de poblaciones vulnerables.', 'Para animales u otros sujetos, cumple bienestar y normativa específica.', 'La publicación no debe causar daños previsibles adicionales.', 'No infieras que consentimiento para investigar incluye consentimiento para publicar identidad, imágenes o datos abiertos.'], citationTreatment: ['Cita códigos, leyes o guías cuando se invoquen; el consentimiento de una persona no es una referencia bibliográfica.'], referenceTreatment: ['Referencia autoridades recuperables citadas y conserva formularios de consentimiento como documentación protegida.'] }),
  'confidentiality-protection': verified({ id: 'confidentiality-protection', label: 'Protección de la confidencialidad', manualSection: '1.19', manualPrintedPages: '22-23', rules: ['Elimina o modifica información identificable cuando sea necesario y declara alteraciones que afecten interpretación.', 'Obtén consentimiento explícito para revelar identidad, fotografía, caso o información reconocible.', 'Evalúa reidentificación por combinación de datos y protege archivos y transferencias.', 'Un seudónimo no garantiza anonimato.', 'Equilibra detalle científico y protección; no inventes datos para ocultar identidad sin avisar que fueron modificados.'], citationTreatment: ['Las comunicaciones confidenciales no se incluyen en referencias; si se citan fuera del estudio, usa comunicación personal con autorización y fecha.', 'Participantes del propio estudio siguen la regla de datos de investigación.'], referenceTreatment: ['No publiques documentos confidenciales como fuentes recuperables; referencia solo versiones públicas autorizadas.'], refuseWhen: ['El contenido permitiría reidentificación no consentida.', 'No se verificó autorización para imagen, nombre, caso o cita.', 'Se pide revelar datos privados o sensibles.'] }),
  'conflicts-of-interest': verified({ id: 'conflicts-of-interest', label: 'Conflictos de intereses', manualSection: '1.20', manualPrintedPages: '23-24', rules: ['Declara intereses financieros, profesionales, personales o institucionales que puedan percibirse como influyentes.', 'Revela financiación y papel del patrocinador en diseño, análisis, redacción y publicación.', 'La existencia de un conflicto no invalida automáticamente el trabajo; ocultarlo impide evaluarlo.', 'Sigue el formulario y política de la revista o institución.'], citationTreatment: ['Una declaración de conflicto no sustituye citar las fuentes ni convierte al financiador en autor.'], referenceTreatment: ['Financiación y conflictos se declaran en la sección correspondiente, no como referencias salvo que una obra del financiador sea citada.'] }),
  'publication-credit': verified({ id: 'publication-credit', label: 'Crédito de publicación', manualSection: '1.21', manualPrintedPages: '24-25', rules: ['Atribuye autoría solo a quienes hicieron contribuciones sustanciales y asumen responsabilidad por el trabajo.', 'Reconoce contribuciones menores en agradecimientos u otra taxonomía, con consentimiento cuando sea necesario.', 'No concedas autoría honoraria ni omitas autoría merecida.', 'Las tareas administrativas, financiación o supervisión por sí solas no garantizan autoría.', 'Documenta contribuciones y acuerdos temprano.'], citationTreatment: ['Citar la obra de una persona no le concede autoría del nuevo trabajo; usar su idea exige cita aunque también sea colaboradora.'], referenceTreatment: ['La lista de autores pertenece al nuevo trabajo; las obras previas de colaboradores se referencian solo si se citan.'] }),
  'author-order': verified({ id: 'author-order', label: 'Orden de los autores', manualSection: '1.22', manualPrintedPages: '25', rules: ['Determina el orden según contribuciones y convenciones disciplinares mediante acuerdo informado.', 'Discute y actualiza el acuerdo cuando cambien las contribuciones.', 'En trabajos derivados de estudiantes, reconoce adecuadamente la contribución principal del estudiante según ética y política.', 'No uses jerarquía, cargo o financiación para imponer un orden engañoso.'], citationTreatment: ['El orden de autores de una fuente citada se conserva exactamente en la referencia; no se reordena alfabéticamente.'], referenceTreatment: ['Transcribe autores en el orden publicado y aplica la elipsis solo conforme a la regla de 21 o más autores.'] }),
  'reviewer-conflict-during-review': verified({ id: 'reviewer-conflict-during-review', label: 'Conflicto de revisores durante la revisión', manualSection: '1.23', manualPrintedPages: '25-26', rules: ['Un revisor debe declarar conflictos, respetar confidencialidad y rechazar la revisión cuando no pueda ser imparcial.', 'No use ideas, datos o texto del manuscrito antes de su publicación ni comparta el documento.', 'No contacte autores fuera del proceso ni retrase para obtener ventaja.', 'Destruya o proteja copias conforme a la política.'], citationTreatment: ['Un manuscrito confidencial revisado no puede citarse ni usarse sin autorización; si luego se publica, cita la versión pública.'], referenceTreatment: ['No agregues a referencias un manuscrito confidencial inaccesible basándote solo en la revisión.'], refuseWhen: ['Se pide usar o divulgar contenido de una revisión confidencial.', 'Existe un conflicto no resuelto.', 'No hay autorización para citar el manuscrito inédito.'] }),
  'unpublished-manuscript-rights': verified({ id: 'unpublished-manuscript-rights', label: 'Derechos sobre manuscritos inéditos', manualSection: '1.24', manualPrintedPages: '26', rules: ['Los autores conservan derechos sobre ideas y texto de manuscritos inéditos y compartidos confidencialmente.', 'No cites, distribuyas, reproduzcas ni uses el contenido sin permiso.', 'Una presentación en aula, revisión o correspondencia no convierte el manuscrito en fuente pública.', 'Cuando exista versión pública autorizada, usa y cita esa versión.'], citationTreatment: ['Con permiso, un manuscrito recuperable puede citarse según su estado; si no es recuperable, trátalo como comunicación personal en el texto.', 'No atribuyas un manuscrito confidencial sin poder revelar o verificar la fuente.'], referenceTreatment: ['Una obra públicamente disponible puede llevar referencia de manuscrito/preprint; una comunicación no recuperable no entra en la lista.'] }),
  'ethical-compliance-checklist': verified({ id: 'ethical-compliance-checklist', label: 'Lista de verificación de cumplimiento ético', manualSection: '1.25', manualPrintedPages: '26', rules: ['Antes de enviar, verifica aprobación, consentimiento, privacidad, exactitud, datos, duplicación, atribución, autoría, conflictos, derechos y permisos.', 'Confirma que todos los autores aprobaron la versión y las declaraciones.', 'Comprueba citas y referencias bidireccionalmente y revisa correcciones o retractaciones de fuentes críticas.', 'Conserva evidencia de cada certificación y resuelve pendientes antes de marcar cumplimiento.', 'La lista es control final, no sustituto de planificación ética.'], citationTreatment: ['Verifica que toda idea, texto, dato y material ajeno tenga la forma de cita requerida y un localizador real cuando sea textual.'], referenceTreatment: ['Comprueba que cada cita recuperable tenga entrada, cada entrada esté citada y ningún metadato se haya inventado.'], refuseWhen: ['Queda cualquier requisito material sin verificar.', 'La persona responsable no puede aportar evidencia de aprobación, permiso o autoría.', 'Se pide emitir una certificación global basándose solo en una revisión superficial.'] }),
};

export function getPrinciplesEthicsRule(id: PrinciplesEthicsRuleId): Apa7VerifiedPrinciplesEthicsRule {
  return principlesEthicsRules[id];
}
